// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/c4erries/mint/internal/rtc/application"
	mock "github.com/stretchr/testify/mock"
)

// NewLiveKitClient creates a new instance of LiveKitClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLiveKitClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *LiveKitClient {
	mock := &LiveKitClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// LiveKitClient is an autogenerated mock type for the LiveKitClient type
type LiveKitClient struct {
	mock.Mock
}

type LiveKitClient_Expecter struct {
	mock *mock.Mock
}

func (_m *LiveKitClient) EXPECT() *LiveKitClient_Expecter {
	return &LiveKitClient_Expecter{mock: &_m.Mock}
}

// IssueToken provides a mock function for the type LiveKitClient
func (_mock *LiveKitClient) IssueToken(ctx context.Context, request application.LiveKitTokenRequest) (application.LiveKitIssuedToken, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for IssueToken")
	}

	var r0 application.LiveKitIssuedToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, application.LiveKitTokenRequest) (application.LiveKitIssuedToken, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, application.LiveKitTokenRequest) application.LiveKitIssuedToken); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Get(0).(application.LiveKitIssuedToken)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, application.LiveKitTokenRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LiveKitClient_IssueToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IssueToken'
type LiveKitClient_IssueToken_Call struct {
	*mock.Call
}

// IssueToken is a helper method to define mock.On call
//   - ctx context.Context
//   - request application.LiveKitTokenRequest
func (_e *LiveKitClient_Expecter) IssueToken(ctx interface{}, request interface{}) *LiveKitClient_IssueToken_Call {
	return &LiveKitClient_IssueToken_Call{Call: _e.mock.On("IssueToken", ctx, request)}
}

func (_c *LiveKitClient_IssueToken_Call) Run(run func(ctx context.Context, request application.LiveKitTokenRequest)) *LiveKitClient_IssueToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 application.LiveKitTokenRequest
		if args[1] != nil {
			arg1 = args[1].(application.LiveKitTokenRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LiveKitClient_IssueToken_Call) Return(liveKitIssuedToken application.LiveKitIssuedToken, err error) *LiveKitClient_IssueToken_Call {
	_c.Call.Return(liveKitIssuedToken, err)
	return _c
}

func (_c *LiveKitClient_IssueToken_Call) RunAndReturn(run func(ctx context.Context, request application.LiveKitTokenRequest) (application.LiveKitIssuedToken, error)) *LiveKitClient_IssueToken_Call {
	_c.Call.Return(run)
	return _c
}
