// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/c4erries/mint/internal/rtc/domain"
	mock "github.com/stretchr/testify/mock"
)

// MediaAccessGrantRepository is an autogenerated mock type for the MediaAccessGrantRepository type
type MediaAccessGrantRepository struct {
	mock.Mock
}

type MediaAccessGrantRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MediaAccessGrantRepository) EXPECT() *MediaAccessGrantRepository_Expecter {
	return &MediaAccessGrantRepository_Expecter{mock: &_m.Mock}
}

// GetGrant provides a mock function with given fields: ctx, tokenID
func (_m *MediaAccessGrantRepository) GetGrant(ctx context.Context, tokenID string) (domain.MediaAccessGrant, error) {
	ret := _m.Called(ctx, tokenID)

	if len(ret) == 0 {
		panic("no return value specified for GetGrant")
	}

	var r0 domain.MediaAccessGrant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.MediaAccessGrant, error)); ok {
		return rf(ctx, tokenID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.MediaAccessGrant); ok {
		r0 = rf(ctx, tokenID)
	} else {
		r0 = ret.Get(0).(domain.MediaAccessGrant)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MediaAccessGrantRepository_GetGrant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGrant'
type MediaAccessGrantRepository_GetGrant_Call struct {
	*mock.Call
}

// GetGrant is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenID string
func (_e *MediaAccessGrantRepository_Expecter) GetGrant(ctx interface{}, tokenID interface{}) *MediaAccessGrantRepository_GetGrant_Call {
	return &MediaAccessGrantRepository_GetGrant_Call{Call: _e.mock.On("GetGrant", ctx, tokenID)}
}

func (_c *MediaAccessGrantRepository_GetGrant_Call) Run(run func(ctx context.Context, tokenID string)) *MediaAccessGrantRepository_GetGrant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MediaAccessGrantRepository_GetGrant_Call) Return(_a0 domain.MediaAccessGrant, _a1 error) *MediaAccessGrantRepository_GetGrant_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MediaAccessGrantRepository_GetGrant_Call) RunAndReturn(run func(context.Context, string) (domain.MediaAccessGrant, error)) *MediaAccessGrantRepository_GetGrant_Call {
	_c.Call.Return(run)
	return _c
}

// GetGrantByCommandID provides a mock function with given fields: ctx, commandID
func (_m *MediaAccessGrantRepository) GetGrantByCommandID(ctx context.Context, commandID string) (domain.MediaAccessGrant, error) {
	ret := _m.Called(ctx, commandID)

	if len(ret) == 0 {
		panic("no return value specified for GetGrantByCommandID")
	}

	var r0 domain.MediaAccessGrant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.MediaAccessGrant, error)); ok {
		return rf(ctx, commandID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.MediaAccessGrant); ok {
		r0 = rf(ctx, commandID)
	} else {
		r0 = ret.Get(0).(domain.MediaAccessGrant)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, commandID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MediaAccessGrantRepository_GetGrantByCommandID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGrantByCommandID'
type MediaAccessGrantRepository_GetGrantByCommandID_Call struct {
	*mock.Call
}

// GetGrantByCommandID is a helper method to define mock.On call
//   - ctx context.Context
//   - commandID string
func (_e *MediaAccessGrantRepository_Expecter) GetGrantByCommandID(ctx interface{}, commandID interface{}) *MediaAccessGrantRepository_GetGrantByCommandID_Call {
	return &MediaAccessGrantRepository_GetGrantByCommandID_Call{Call: _e.mock.On("GetGrantByCommandID", ctx, commandID)}
}

func (_c *MediaAccessGrantRepository_GetGrantByCommandID_Call) Run(run func(ctx context.Context, commandID string)) *MediaAccessGrantRepository_GetGrantByCommandID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MediaAccessGrantRepository_GetGrantByCommandID_Call) Return(_a0 domain.MediaAccessGrant, _a1 error) *MediaAccessGrantRepository_GetGrantByCommandID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MediaAccessGrantRepository_GetGrantByCommandID_Call) RunAndReturn(run func(context.Context, string) (domain.MediaAccessGrant, error)) *MediaAccessGrantRepository_GetGrantByCommandID_Call {
	_c.Call.Return(run)
	return _c
}

// SaveGrant provides a mock function with given fields: ctx, grant
func (_m *MediaAccessGrantRepository) SaveGrant(ctx context.Context, grant domain.MediaAccessGrant) error {
	ret := _m.Called(ctx, grant)

	if len(ret) == 0 {
		panic("no return value specified for SaveGrant")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.MediaAccessGrant) error); ok {
		r0 = rf(ctx, grant)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MediaAccessGrantRepository_SaveGrant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveGrant'
type MediaAccessGrantRepository_SaveGrant_Call struct {
	*mock.Call
}

// SaveGrant is a helper method to define mock.On call
//   - ctx context.Context
//   - grant domain.MediaAccessGrant
func (_e *MediaAccessGrantRepository_Expecter) SaveGrant(ctx interface{}, grant interface{}) *MediaAccessGrantRepository_SaveGrant_Call {
	return &MediaAccessGrantRepository_SaveGrant_Call{Call: _e.mock.On("SaveGrant", ctx, grant)}
}

func (_c *MediaAccessGrantRepository_SaveGrant_Call) Run(run func(ctx context.Context, grant domain.MediaAccessGrant)) *MediaAccessGrantRepository_SaveGrant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.MediaAccessGrant))
	})
	return _c
}

func (_c *MediaAccessGrantRepository_SaveGrant_Call) Return(_a0 error) *MediaAccessGrantRepository_SaveGrant_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MediaAccessGrantRepository_SaveGrant_Call) RunAndReturn(run func(context.Context, domain.MediaAccessGrant) error) *MediaAccessGrantRepository_SaveGrant_Call {
	_c.Call.Return(run)
	return _c
}

// NewMediaAccessGrantRepository creates a new instance of MediaAccessGrantRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMediaAccessGrantRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MediaAccessGrantRepository {
	mock := &MediaAccessGrantRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
