// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/c4erries/mint/internal/rtc/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMediaAccessGrantRepository creates a new instance of MediaAccessGrantRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMediaAccessGrantRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MediaAccessGrantRepository {
	mock := &MediaAccessGrantRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MediaAccessGrantRepository is an autogenerated mock type for the MediaAccessGrantRepository type
type MediaAccessGrantRepository struct {
	mock.Mock
}

type MediaAccessGrantRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MediaAccessGrantRepository) EXPECT() *MediaAccessGrantRepository_Expecter {
	return &MediaAccessGrantRepository_Expecter{mock: &_m.Mock}
}

// GetGrant provides a mock function for the type MediaAccessGrantRepository
func (_mock *MediaAccessGrantRepository) GetGrant(ctx context.Context, tokenID string) (domain.MediaAccessGrant, error) {
	ret := _mock.Called(ctx, tokenID)

	if len(ret) == 0 {
		panic("no return value specified for GetGrant")
	}

	var r0 domain.MediaAccessGrant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.MediaAccessGrant, error)); ok {
		return returnFunc(ctx, tokenID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.MediaAccessGrant); ok {
		r0 = returnFunc(ctx, tokenID)
	} else {
		r0 = ret.Get(0).(domain.MediaAccessGrant)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tokenID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MediaAccessGrantRepository_GetGrant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGrant'
type MediaAccessGrantRepository_GetGrant_Call struct {
	*mock.Call
}

// GetGrant is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenID string
func (_e *MediaAccessGrantRepository_Expecter) GetGrant(ctx interface{}, tokenID interface{}) *MediaAccessGrantRepository_GetGrant_Call {
	return &MediaAccessGrantRepository_GetGrant_Call{Call: _e.mock.On("GetGrant", ctx, tokenID)}
}

func (_c *MediaAccessGrantRepository_GetGrant_Call) Run(run func(ctx context.Context, tokenID string)) *MediaAccessGrantRepository_GetGrant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MediaAccessGrantRepository_GetGrant_Call) Return(mediaAccessGrant domain.MediaAccessGrant, err error) *MediaAccessGrantRepository_GetGrant_Call {
	_c.Call.Return(mediaAccessGrant, err)
	return _c
}

func (_c *MediaAccessGrantRepository_GetGrant_Call) RunAndReturn(run func(ctx context.Context, tokenID string) (domain.MediaAccessGrant, error)) *MediaAccessGrantRepository_GetGrant_Call {
	_c.Call.Return(run)
	return _c
}

// GetGrantByCommandID provides a mock function for the type MediaAccessGrantRepository
func (_mock *MediaAccessGrantRepository) GetGrantByCommandID(ctx context.Context, commandID string) (domain.MediaAccessGrant, error) {
	ret := _mock.Called(ctx, commandID)

	if len(ret) == 0 {
		panic("no return value specified for GetGrantByCommandID")
	}

	var r0 domain.MediaAccessGrant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.MediaAccessGrant, error)); ok {
		return returnFunc(ctx, commandID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.MediaAccessGrant); ok {
		r0 = returnFunc(ctx, commandID)
	} else {
		r0 = ret.Get(0).(domain.MediaAccessGrant)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, commandID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MediaAccessGrantRepository_GetGrantByCommandID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGrantByCommandID'
type MediaAccessGrantRepository_GetGrantByCommandID_Call struct {
	*mock.Call
}

// GetGrantByCommandID is a helper method to define mock.On call
//   - ctx context.Context
//   - commandID string
func (_e *MediaAccessGrantRepository_Expecter) GetGrantByCommandID(ctx interface{}, commandID interface{}) *MediaAccessGrantRepository_GetGrantByCommandID_Call {
	return &MediaAccessGrantRepository_GetGrantByCommandID_Call{Call: _e.mock.On("GetGrantByCommandID", ctx, commandID)}
}

func (_c *MediaAccessGrantRepository_GetGrantByCommandID_Call) Run(run func(ctx context.Context, commandID string)) *MediaAccessGrantRepository_GetGrantByCommandID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MediaAccessGrantRepository_GetGrantByCommandID_Call) Return(mediaAccessGrant domain.MediaAccessGrant, err error) *MediaAccessGrantRepository_GetGrantByCommandID_Call {
	_c.Call.Return(mediaAccessGrant, err)
	return _c
}

func (_c *MediaAccessGrantRepository_GetGrantByCommandID_Call) RunAndReturn(run func(ctx context.Context, commandID string) (domain.MediaAccessGrant, error)) *MediaAccessGrantRepository_GetGrantByCommandID_Call {
	_c.Call.Return(run)
	return _c
}

// SaveGrant provides a mock function for the type MediaAccessGrantRepository
func (_mock *MediaAccessGrantRepository) SaveGrant(ctx context.Context, grant domain.MediaAccessGrant) error {
	ret := _mock.Called(ctx, grant)

	if len(ret) == 0 {
		panic("no return value specified for SaveGrant")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.MediaAccessGrant) error); ok {
		r0 = returnFunc(ctx, grant)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MediaAccessGrantRepository_SaveGrant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveGrant'
type MediaAccessGrantRepository_SaveGrant_Call struct {
	*mock.Call
}

// SaveGrant is a helper method to define mock.On call
//   - ctx context.Context
//   - grant domain.MediaAccessGrant
func (_e *MediaAccessGrantRepository_Expecter) SaveGrant(ctx interface{}, grant interface{}) *MediaAccessGrantRepository_SaveGrant_Call {
	return &MediaAccessGrantRepository_SaveGrant_Call{Call: _e.mock.On("SaveGrant", ctx, grant)}
}

func (_c *MediaAccessGrantRepository_SaveGrant_Call) Run(run func(ctx context.Context, grant domain.MediaAccessGrant)) *MediaAccessGrantRepository_SaveGrant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.MediaAccessGrant
		if args[1] != nil {
			arg1 = args[1].(domain.MediaAccessGrant)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MediaAccessGrantRepository_SaveGrant_Call) Return(err error) *MediaAccessGrantRepository_SaveGrant_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MediaAccessGrantRepository_SaveGrant_Call) RunAndReturn(run func(ctx context.Context, grant domain.MediaAccessGrant) error) *MediaAccessGrantRepository_SaveGrant_Call {
	_c.Call.Return(run)
	return _c
}
