// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewPermissionChecker creates a new instance of PermissionChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPermissionChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *PermissionChecker {
	mock := &PermissionChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PermissionChecker is an autogenerated mock type for the PermissionChecker type
type PermissionChecker struct {
	mock.Mock
}

type PermissionChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *PermissionChecker) EXPECT() *PermissionChecker_Expecter {
	return &PermissionChecker_Expecter{mock: &_m.Mock}
}

// CanJoinVoiceChannel provides a mock function for the type PermissionChecker
func (_mock *PermissionChecker) CanJoinVoiceChannel(ctx context.Context, workspaceID string, channelID string, userID string) (bool, error) {
	ret := _mock.Called(ctx, workspaceID, channelID, userID)

	if len(ret) == 0 {
		panic("no return value specified for CanJoinVoiceChannel")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (bool, error)); ok {
		return returnFunc(ctx, workspaceID, channelID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) bool); ok {
		r0 = returnFunc(ctx, workspaceID, channelID, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, workspaceID, channelID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PermissionChecker_CanJoinVoiceChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanJoinVoiceChannel'
type PermissionChecker_CanJoinVoiceChannel_Call struct {
	*mock.Call
}

// CanJoinVoiceChannel is a helper method to define mock.On call
//   - ctx context.Context
//   - workspaceID string
//   - channelID string
//   - userID string
func (_e *PermissionChecker_Expecter) CanJoinVoiceChannel(ctx interface{}, workspaceID interface{}, channelID interface{}, userID interface{}) *PermissionChecker_CanJoinVoiceChannel_Call {
	return &PermissionChecker_CanJoinVoiceChannel_Call{Call: _e.mock.On("CanJoinVoiceChannel", ctx, workspaceID, channelID, userID)}
}

func (_c *PermissionChecker_CanJoinVoiceChannel_Call) Run(run func(ctx context.Context, workspaceID string, channelID string, userID string)) *PermissionChecker_CanJoinVoiceChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *PermissionChecker_CanJoinVoiceChannel_Call) Return(b bool, err error) *PermissionChecker_CanJoinVoiceChannel_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *PermissionChecker_CanJoinVoiceChannel_Call) RunAndReturn(run func(ctx context.Context, workspaceID string, channelID string, userID string) (bool, error)) *PermissionChecker_CanJoinVoiceChannel_Call {
	_c.Call.Return(run)
	return _c
}
