// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// PermissionChecker is an autogenerated mock type for the PermissionChecker type
type PermissionChecker struct {
	mock.Mock
}

type PermissionChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *PermissionChecker) EXPECT() *PermissionChecker_Expecter {
	return &PermissionChecker_Expecter{mock: &_m.Mock}
}

// CanJoinVoiceChannel provides a mock function with given fields: ctx, workspaceID, channelID, userID
func (_m *PermissionChecker) CanJoinVoiceChannel(ctx context.Context, workspaceID string, channelID string, userID string) (bool, error) {
	ret := _m.Called(ctx, workspaceID, channelID, userID)

	if len(ret) == 0 {
		panic("no return value specified for CanJoinVoiceChannel")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (bool, error)); ok {
		return rf(ctx, workspaceID, channelID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) bool); ok {
		r0 = rf(ctx, workspaceID, channelID, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, workspaceID, channelID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PermissionChecker_CanJoinVoiceChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanJoinVoiceChannel'
type PermissionChecker_CanJoinVoiceChannel_Call struct {
	*mock.Call
}

// CanJoinVoiceChannel is a helper method to define mock.On call
//   - ctx context.Context
//   - workspaceID string
//   - channelID string
//   - userID string
func (_e *PermissionChecker_Expecter) CanJoinVoiceChannel(ctx interface{}, workspaceID interface{}, channelID interface{}, userID interface{}) *PermissionChecker_CanJoinVoiceChannel_Call {
	return &PermissionChecker_CanJoinVoiceChannel_Call{Call: _e.mock.On("CanJoinVoiceChannel", ctx, workspaceID, channelID, userID)}
}

func (_c *PermissionChecker_CanJoinVoiceChannel_Call) Run(run func(ctx context.Context, workspaceID string, channelID string, userID string)) *PermissionChecker_CanJoinVoiceChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *PermissionChecker_CanJoinVoiceChannel_Call) Return(_a0 bool, _a1 error) *PermissionChecker_CanJoinVoiceChannel_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PermissionChecker_CanJoinVoiceChannel_Call) RunAndReturn(run func(context.Context, string, string, string) (bool, error)) *PermissionChecker_CanJoinVoiceChannel_Call {
	_c.Call.Return(run)
	return _c
}

// NewPermissionChecker creates a new instance of PermissionChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPermissionChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *PermissionChecker {
	mock := &PermissionChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
