// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	application "github.com/c4erries/mint/internal/rtc/application"

	domain "github.com/c4erries/mint/internal/rtc/domain"

	mock "github.com/stretchr/testify/mock"
)

// VoiceRoomWriteTx is an autogenerated mock type for the VoiceRoomWriteTx type
type VoiceRoomWriteTx struct {
	mock.Mock
}

type VoiceRoomWriteTx_Expecter struct {
	mock *mock.Mock
}

func (_m *VoiceRoomWriteTx) EXPECT() *VoiceRoomWriteTx_Expecter {
	return &VoiceRoomWriteTx_Expecter{mock: &_m.Mock}
}

// AppendOutbox provides a mock function with given fields: ctx, message
func (_m *VoiceRoomWriteTx) AppendOutbox(ctx context.Context, message application.OutboxMessage) error {
	ret := _m.Called(ctx, message)

	if len(ret) == 0 {
		panic("no return value specified for AppendOutbox")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, application.OutboxMessage) error); ok {
		r0 = rf(ctx, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VoiceRoomWriteTx_AppendOutbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppendOutbox'
type VoiceRoomWriteTx_AppendOutbox_Call struct {
	*mock.Call
}

// AppendOutbox is a helper method to define mock.On call
//   - ctx context.Context
//   - message application.OutboxMessage
func (_e *VoiceRoomWriteTx_Expecter) AppendOutbox(ctx interface{}, message interface{}) *VoiceRoomWriteTx_AppendOutbox_Call {
	return &VoiceRoomWriteTx_AppendOutbox_Call{Call: _e.mock.On("AppendOutbox", ctx, message)}
}

func (_c *VoiceRoomWriteTx_AppendOutbox_Call) Run(run func(ctx context.Context, message application.OutboxMessage)) *VoiceRoomWriteTx_AppendOutbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(application.OutboxMessage))
	})
	return _c
}

func (_c *VoiceRoomWriteTx_AppendOutbox_Call) Return(_a0 error) *VoiceRoomWriteTx_AppendOutbox_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VoiceRoomWriteTx_AppendOutbox_Call) RunAndReturn(run func(context.Context, application.OutboxMessage) error) *VoiceRoomWriteTx_AppendOutbox_Call {
	_c.Call.Return(run)
	return _c
}

// GetBindingByChannel provides a mock function with given fields: ctx, workspaceID, channelID
func (_m *VoiceRoomWriteTx) GetBindingByChannel(ctx context.Context, workspaceID string, channelID string) (*domain.VoiceChannelBinding, error) {
	ret := _m.Called(ctx, workspaceID, channelID)

	if len(ret) == 0 {
		panic("no return value specified for GetBindingByChannel")
	}

	var r0 *domain.VoiceChannelBinding
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.VoiceChannelBinding, error)); ok {
		return rf(ctx, workspaceID, channelID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.VoiceChannelBinding); ok {
		r0 = rf(ctx, workspaceID, channelID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.VoiceChannelBinding)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, workspaceID, channelID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VoiceRoomWriteTx_GetBindingByChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBindingByChannel'
type VoiceRoomWriteTx_GetBindingByChannel_Call struct {
	*mock.Call
}

// GetBindingByChannel is a helper method to define mock.On call
//   - ctx context.Context
//   - workspaceID string
//   - channelID string
func (_e *VoiceRoomWriteTx_Expecter) GetBindingByChannel(ctx interface{}, workspaceID interface{}, channelID interface{}) *VoiceRoomWriteTx_GetBindingByChannel_Call {
	return &VoiceRoomWriteTx_GetBindingByChannel_Call{Call: _e.mock.On("GetBindingByChannel", ctx, workspaceID, channelID)}
}

func (_c *VoiceRoomWriteTx_GetBindingByChannel_Call) Run(run func(ctx context.Context, workspaceID string, channelID string)) *VoiceRoomWriteTx_GetBindingByChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *VoiceRoomWriteTx_GetBindingByChannel_Call) Return(_a0 *domain.VoiceChannelBinding, _a1 error) *VoiceRoomWriteTx_GetBindingByChannel_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *VoiceRoomWriteTx_GetBindingByChannel_Call) RunAndReturn(run func(context.Context, string, string) (*domain.VoiceChannelBinding, error)) *VoiceRoomWriteTx_GetBindingByChannel_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoom provides a mock function with given fields: ctx, roomID
func (_m *VoiceRoomWriteTx) GetRoom(ctx context.Context, roomID string) (*domain.VoiceRoom, error) {
	ret := _m.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for GetRoom")
	}

	var r0 *domain.VoiceRoom
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.VoiceRoom, error)); ok {
		return rf(ctx, roomID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.VoiceRoom); ok {
		r0 = rf(ctx, roomID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.VoiceRoom)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, roomID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VoiceRoomWriteTx_GetRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoom'
type VoiceRoomWriteTx_GetRoom_Call struct {
	*mock.Call
}

// GetRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID string
func (_e *VoiceRoomWriteTx_Expecter) GetRoom(ctx interface{}, roomID interface{}) *VoiceRoomWriteTx_GetRoom_Call {
	return &VoiceRoomWriteTx_GetRoom_Call{Call: _e.mock.On("GetRoom", ctx, roomID)}
}

func (_c *VoiceRoomWriteTx_GetRoom_Call) Run(run func(ctx context.Context, roomID string)) *VoiceRoomWriteTx_GetRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *VoiceRoomWriteTx_GetRoom_Call) Return(_a0 *domain.VoiceRoom, _a1 error) *VoiceRoomWriteTx_GetRoom_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *VoiceRoomWriteTx_GetRoom_Call) RunAndReturn(run func(context.Context, string) (*domain.VoiceRoom, error)) *VoiceRoomWriteTx_GetRoom_Call {
	_c.Call.Return(run)
	return _c
}

// IsCommandProcessed provides a mock function with given fields: ctx, commandID
func (_m *VoiceRoomWriteTx) IsCommandProcessed(ctx context.Context, commandID string) (bool, error) {
	ret := _m.Called(ctx, commandID)

	if len(ret) == 0 {
		panic("no return value specified for IsCommandProcessed")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, commandID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, commandID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, commandID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VoiceRoomWriteTx_IsCommandProcessed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsCommandProcessed'
type VoiceRoomWriteTx_IsCommandProcessed_Call struct {
	*mock.Call
}

// IsCommandProcessed is a helper method to define mock.On call
//   - ctx context.Context
//   - commandID string
func (_e *VoiceRoomWriteTx_Expecter) IsCommandProcessed(ctx interface{}, commandID interface{}) *VoiceRoomWriteTx_IsCommandProcessed_Call {
	return &VoiceRoomWriteTx_IsCommandProcessed_Call{Call: _e.mock.On("IsCommandProcessed", ctx, commandID)}
}

func (_c *VoiceRoomWriteTx_IsCommandProcessed_Call) Run(run func(ctx context.Context, commandID string)) *VoiceRoomWriteTx_IsCommandProcessed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *VoiceRoomWriteTx_IsCommandProcessed_Call) Return(_a0 bool, _a1 error) *VoiceRoomWriteTx_IsCommandProcessed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *VoiceRoomWriteTx_IsCommandProcessed_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *VoiceRoomWriteTx_IsCommandProcessed_Call {
	_c.Call.Return(run)
	return _c
}

// MarkCommandProcessed provides a mock function with given fields: ctx, commandID
func (_m *VoiceRoomWriteTx) MarkCommandProcessed(ctx context.Context, commandID string) error {
	ret := _m.Called(ctx, commandID)

	if len(ret) == 0 {
		panic("no return value specified for MarkCommandProcessed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, commandID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VoiceRoomWriteTx_MarkCommandProcessed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkCommandProcessed'
type VoiceRoomWriteTx_MarkCommandProcessed_Call struct {
	*mock.Call
}

// MarkCommandProcessed is a helper method to define mock.On call
//   - ctx context.Context
//   - commandID string
func (_e *VoiceRoomWriteTx_Expecter) MarkCommandProcessed(ctx interface{}, commandID interface{}) *VoiceRoomWriteTx_MarkCommandProcessed_Call {
	return &VoiceRoomWriteTx_MarkCommandProcessed_Call{Call: _e.mock.On("MarkCommandProcessed", ctx, commandID)}
}

func (_c *VoiceRoomWriteTx_MarkCommandProcessed_Call) Run(run func(ctx context.Context, commandID string)) *VoiceRoomWriteTx_MarkCommandProcessed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *VoiceRoomWriteTx_MarkCommandProcessed_Call) Return(_a0 error) *VoiceRoomWriteTx_MarkCommandProcessed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VoiceRoomWriteTx_MarkCommandProcessed_Call) RunAndReturn(run func(context.Context, string) error) *VoiceRoomWriteTx_MarkCommandProcessed_Call {
	_c.Call.Return(run)
	return _c
}

// SaveBinding provides a mock function with given fields: ctx, binding
func (_m *VoiceRoomWriteTx) SaveBinding(ctx context.Context, binding *domain.VoiceChannelBinding) error {
	ret := _m.Called(ctx, binding)

	if len(ret) == 0 {
		panic("no return value specified for SaveBinding")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.VoiceChannelBinding) error); ok {
		r0 = rf(ctx, binding)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VoiceRoomWriteTx_SaveBinding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveBinding'
type VoiceRoomWriteTx_SaveBinding_Call struct {
	*mock.Call
}

// SaveBinding is a helper method to define mock.On call
//   - ctx context.Context
//   - binding *domain.VoiceChannelBinding
func (_e *VoiceRoomWriteTx_Expecter) SaveBinding(ctx interface{}, binding interface{}) *VoiceRoomWriteTx_SaveBinding_Call {
	return &VoiceRoomWriteTx_SaveBinding_Call{Call: _e.mock.On("SaveBinding", ctx, binding)}
}

func (_c *VoiceRoomWriteTx_SaveBinding_Call) Run(run func(ctx context.Context, binding *domain.VoiceChannelBinding)) *VoiceRoomWriteTx_SaveBinding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.VoiceChannelBinding))
	})
	return _c
}

func (_c *VoiceRoomWriteTx_SaveBinding_Call) Return(_a0 error) *VoiceRoomWriteTx_SaveBinding_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VoiceRoomWriteTx_SaveBinding_Call) RunAndReturn(run func(context.Context, *domain.VoiceChannelBinding) error) *VoiceRoomWriteTx_SaveBinding_Call {
	_c.Call.Return(run)
	return _c
}

// SaveRoom provides a mock function with given fields: ctx, room
func (_m *VoiceRoomWriteTx) SaveRoom(ctx context.Context, room *domain.VoiceRoom) error {
	ret := _m.Called(ctx, room)

	if len(ret) == 0 {
		panic("no return value specified for SaveRoom")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.VoiceRoom) error); ok {
		r0 = rf(ctx, room)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VoiceRoomWriteTx_SaveRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveRoom'
type VoiceRoomWriteTx_SaveRoom_Call struct {
	*mock.Call
}

// SaveRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - room *domain.VoiceRoom
func (_e *VoiceRoomWriteTx_Expecter) SaveRoom(ctx interface{}, room interface{}) *VoiceRoomWriteTx_SaveRoom_Call {
	return &VoiceRoomWriteTx_SaveRoom_Call{Call: _e.mock.On("SaveRoom", ctx, room)}
}

func (_c *VoiceRoomWriteTx_SaveRoom_Call) Run(run func(ctx context.Context, room *domain.VoiceRoom)) *VoiceRoomWriteTx_SaveRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.VoiceRoom))
	})
	return _c
}

func (_c *VoiceRoomWriteTx_SaveRoom_Call) Return(_a0 error) *VoiceRoomWriteTx_SaveRoom_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VoiceRoomWriteTx_SaveRoom_Call) RunAndReturn(run func(context.Context, *domain.VoiceRoom) error) *VoiceRoomWriteTx_SaveRoom_Call {
	_c.Call.Return(run)
	return _c
}

// NewVoiceRoomWriteTx creates a new instance of VoiceRoomWriteTx. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVoiceRoomWriteTx(t interface {
	mock.TestingT
	Cleanup(func())
}) *VoiceRoomWriteTx {
	mock := &VoiceRoomWriteTx{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
