// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	application "github.com/c4erries/mint/internal/rtc/application"

	mock "github.com/stretchr/testify/mock"
)

// VoiceRoomReadRepository is an autogenerated mock type for the VoiceRoomReadRepository type
type VoiceRoomReadRepository struct {
	mock.Mock
}

type VoiceRoomReadRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *VoiceRoomReadRepository) EXPECT() *VoiceRoomReadRepository_Expecter {
	return &VoiceRoomReadRepository_Expecter{mock: &_m.Mock}
}

// GetVoiceChannelBinding provides a mock function with given fields: ctx, workspaceID, channelID
func (_m *VoiceRoomReadRepository) GetVoiceChannelBinding(ctx context.Context, workspaceID string, channelID string) (application.VoiceChannelBindingView, error) {
	ret := _m.Called(ctx, workspaceID, channelID)

	if len(ret) == 0 {
		panic("no return value specified for GetVoiceChannelBinding")
	}

	var r0 application.VoiceChannelBindingView
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (application.VoiceChannelBindingView, error)); ok {
		return rf(ctx, workspaceID, channelID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) application.VoiceChannelBindingView); ok {
		r0 = rf(ctx, workspaceID, channelID)
	} else {
		r0 = ret.Get(0).(application.VoiceChannelBindingView)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, workspaceID, channelID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VoiceRoomReadRepository_GetVoiceChannelBinding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVoiceChannelBinding'
type VoiceRoomReadRepository_GetVoiceChannelBinding_Call struct {
	*mock.Call
}

// GetVoiceChannelBinding is a helper method to define mock.On call
//   - ctx context.Context
//   - workspaceID string
//   - channelID string
func (_e *VoiceRoomReadRepository_Expecter) GetVoiceChannelBinding(ctx interface{}, workspaceID interface{}, channelID interface{}) *VoiceRoomReadRepository_GetVoiceChannelBinding_Call {
	return &VoiceRoomReadRepository_GetVoiceChannelBinding_Call{Call: _e.mock.On("GetVoiceChannelBinding", ctx, workspaceID, channelID)}
}

func (_c *VoiceRoomReadRepository_GetVoiceChannelBinding_Call) Run(run func(ctx context.Context, workspaceID string, channelID string)) *VoiceRoomReadRepository_GetVoiceChannelBinding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *VoiceRoomReadRepository_GetVoiceChannelBinding_Call) Return(_a0 application.VoiceChannelBindingView, _a1 error) *VoiceRoomReadRepository_GetVoiceChannelBinding_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *VoiceRoomReadRepository_GetVoiceChannelBinding_Call) RunAndReturn(run func(context.Context, string, string) (application.VoiceChannelBindingView, error)) *VoiceRoomReadRepository_GetVoiceChannelBinding_Call {
	_c.Call.Return(run)
	return _c
}

// GetVoiceRoomState provides a mock function with given fields: ctx, workspaceID, channelID
func (_m *VoiceRoomReadRepository) GetVoiceRoomState(ctx context.Context, workspaceID string, channelID string) (application.VoiceRoomState, error) {
	ret := _m.Called(ctx, workspaceID, channelID)

	if len(ret) == 0 {
		panic("no return value specified for GetVoiceRoomState")
	}

	var r0 application.VoiceRoomState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (application.VoiceRoomState, error)); ok {
		return rf(ctx, workspaceID, channelID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) application.VoiceRoomState); ok {
		r0 = rf(ctx, workspaceID, channelID)
	} else {
		r0 = ret.Get(0).(application.VoiceRoomState)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, workspaceID, channelID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VoiceRoomReadRepository_GetVoiceRoomState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVoiceRoomState'
type VoiceRoomReadRepository_GetVoiceRoomState_Call struct {
	*mock.Call
}

// GetVoiceRoomState is a helper method to define mock.On call
//   - ctx context.Context
//   - workspaceID string
//   - channelID string
func (_e *VoiceRoomReadRepository_Expecter) GetVoiceRoomState(ctx interface{}, workspaceID interface{}, channelID interface{}) *VoiceRoomReadRepository_GetVoiceRoomState_Call {
	return &VoiceRoomReadRepository_GetVoiceRoomState_Call{Call: _e.mock.On("GetVoiceRoomState", ctx, workspaceID, channelID)}
}

func (_c *VoiceRoomReadRepository_GetVoiceRoomState_Call) Run(run func(ctx context.Context, workspaceID string, channelID string)) *VoiceRoomReadRepository_GetVoiceRoomState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *VoiceRoomReadRepository_GetVoiceRoomState_Call) Return(_a0 application.VoiceRoomState, _a1 error) *VoiceRoomReadRepository_GetVoiceRoomState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *VoiceRoomReadRepository_GetVoiceRoomState_Call) RunAndReturn(run func(context.Context, string, string) (application.VoiceRoomState, error)) *VoiceRoomReadRepository_GetVoiceRoomState_Call {
	_c.Call.Return(run)
	return _c
}

// ListVoiceParticipants provides a mock function with given fields: ctx, roomID
func (_m *VoiceRoomReadRepository) ListVoiceParticipants(ctx context.Context, roomID string) ([]application.VoiceParticipant, error) {
	ret := _m.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for ListVoiceParticipants")
	}

	var r0 []application.VoiceParticipant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]application.VoiceParticipant, error)); ok {
		return rf(ctx, roomID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []application.VoiceParticipant); ok {
		r0 = rf(ctx, roomID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]application.VoiceParticipant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, roomID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VoiceRoomReadRepository_ListVoiceParticipants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListVoiceParticipants'
type VoiceRoomReadRepository_ListVoiceParticipants_Call struct {
	*mock.Call
}

// ListVoiceParticipants is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID string
func (_e *VoiceRoomReadRepository_Expecter) ListVoiceParticipants(ctx interface{}, roomID interface{}) *VoiceRoomReadRepository_ListVoiceParticipants_Call {
	return &VoiceRoomReadRepository_ListVoiceParticipants_Call{Call: _e.mock.On("ListVoiceParticipants", ctx, roomID)}
}

func (_c *VoiceRoomReadRepository_ListVoiceParticipants_Call) Run(run func(ctx context.Context, roomID string)) *VoiceRoomReadRepository_ListVoiceParticipants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *VoiceRoomReadRepository_ListVoiceParticipants_Call) Return(_a0 []application.VoiceParticipant, _a1 error) *VoiceRoomReadRepository_ListVoiceParticipants_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *VoiceRoomReadRepository_ListVoiceParticipants_Call) RunAndReturn(run func(context.Context, string) ([]application.VoiceParticipant, error)) *VoiceRoomReadRepository_ListVoiceParticipants_Call {
	_c.Call.Return(run)
	return _c
}

// NewVoiceRoomReadRepository creates a new instance of VoiceRoomReadRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVoiceRoomReadRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *VoiceRoomReadRepository {
	mock := &VoiceRoomReadRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
