// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/rtc/v1/query.proto

package rtcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetVoiceRoomStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	ChannelId     string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVoiceRoomStateRequest) Reset() {
	*x = GetVoiceRoomStateRequest{}
	mi := &file_api_rtc_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVoiceRoomStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVoiceRoomStateRequest) ProtoMessage() {}

func (x *GetVoiceRoomStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtc_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVoiceRoomStateRequest.ProtoReflect.Descriptor instead.
func (*GetVoiceRoomStateRequest) Descriptor() ([]byte, []int) {
	return file_api_rtc_v1_query_proto_rawDescGZIP(), []int{0}
}

func (x *GetVoiceRoomStateRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *GetVoiceRoomStateRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type GetVoiceRoomStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *VoiceRoomState        `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVoiceRoomStateResponse) Reset() {
	*x = GetVoiceRoomStateResponse{}
	mi := &file_api_rtc_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVoiceRoomStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVoiceRoomStateResponse) ProtoMessage() {}

func (x *GetVoiceRoomStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtc_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVoiceRoomStateResponse.ProtoReflect.Descriptor instead.
func (*GetVoiceRoomStateResponse) Descriptor() ([]byte, []int) {
	return file_api_rtc_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *GetVoiceRoomStateResponse) GetState() *VoiceRoomState {
	if x != nil {
		return x.State
	}
	return nil
}

type VoiceRoomState struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RoomId            string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	WorkspaceId       string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	ChannelId         string                 `protobuf:"bytes,3,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Active            bool                   `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	ParticipantCount  int32                  `protobuf:"varint,5,opt,name=participant_count,json=participantCount,proto3" json:"participant_count,omitempty"`
	LastStateChangeAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_state_change_at,json=lastStateChangeAt,proto3" json:"last_state_change_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VoiceRoomState) Reset() {
	*x = VoiceRoomState{}
	mi := &file_api_rtc_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoiceRoomState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoiceRoomState) ProtoMessage() {}

func (x *VoiceRoomState) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtc_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoiceRoomState.ProtoReflect.Descriptor instead.
func (*VoiceRoomState) Descriptor() ([]byte, []int) {
	return file_api_rtc_v1_query_proto_rawDescGZIP(), []int{2}
}

func (x *VoiceRoomState) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *VoiceRoomState) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *VoiceRoomState) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *VoiceRoomState) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *VoiceRoomState) GetParticipantCount() int32 {
	if x != nil {
		return x.ParticipantCount
	}
	return 0
}

func (x *VoiceRoomState) GetLastStateChangeAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastStateChangeAt
	}
	return nil
}

type ListVoiceParticipantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVoiceParticipantsRequest) Reset() {
	*x = ListVoiceParticipantsRequest{}
	mi := &file_api_rtc_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVoiceParticipantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVoiceParticipantsRequest) ProtoMessage() {}

func (x *ListVoiceParticipantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtc_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVoiceParticipantsRequest.ProtoReflect.Descriptor instead.
func (*ListVoiceParticipantsRequest) Descriptor() ([]byte, []int) {
	return file_api_rtc_v1_query_proto_rawDescGZIP(), []int{3}
}

func (x *ListVoiceParticipantsRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type ListVoiceParticipantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Participants  []*VoiceParticipant    `protobuf:"bytes,1,rep,name=participants,proto3" json:"participants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVoiceParticipantsResponse) Reset() {
	*x = ListVoiceParticipantsResponse{}
	mi := &file_api_rtc_v1_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVoiceParticipantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVoiceParticipantsResponse) ProtoMessage() {}

func (x *ListVoiceParticipantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtc_v1_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVoiceParticipantsResponse.ProtoReflect.Descriptor instead.
func (*ListVoiceParticipantsResponse) Descriptor() ([]byte, []int) {
	return file_api_rtc_v1_query_proto_rawDescGZIP(), []int{4}
}

func (x *ListVoiceParticipantsResponse) GetParticipants() []*VoiceParticipant {
	if x != nil {
		return x.Participants
	}
	return nil
}

type VoiceParticipant struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	JoinedAt        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	LeftAt          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=left_at,json=leftAt,proto3" json:"left_at,omitempty"`
	MicrophoneMuted bool                   `protobuf:"varint,4,opt,name=microphone_muted,json=microphoneMuted,proto3" json:"microphone_muted,omitempty"`
	CameraEnabled   bool                   `protobuf:"varint,5,opt,name=camera_enabled,json=cameraEnabled,proto3" json:"camera_enabled,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VoiceParticipant) Reset() {
	*x = VoiceParticipant{}
	mi := &file_api_rtc_v1_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoiceParticipant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoiceParticipant) ProtoMessage() {}

func (x *VoiceParticipant) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtc_v1_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoiceParticipant.ProtoReflect.Descriptor instead.
func (*VoiceParticipant) Descriptor() ([]byte, []int) {
	return file_api_rtc_v1_query_proto_rawDescGZIP(), []int{5}
}

func (x *VoiceParticipant) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *VoiceParticipant) GetJoinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.JoinedAt
	}
	return nil
}

func (x *VoiceParticipant) GetLeftAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LeftAt
	}
	return nil
}

func (x *VoiceParticipant) GetMicrophoneMuted() bool {
	if x != nil {
		return x.MicrophoneMuted
	}
	return false
}

func (x *VoiceParticipant) GetCameraEnabled() bool {
	if x != nil {
		return x.CameraEnabled
	}
	return false
}

type GetVoiceChannelBindingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	ChannelId     string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVoiceChannelBindingRequest) Reset() {
	*x = GetVoiceChannelBindingRequest{}
	mi := &file_api_rtc_v1_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVoiceChannelBindingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVoiceChannelBindingRequest) ProtoMessage() {}

func (x *GetVoiceChannelBindingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtc_v1_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVoiceChannelBindingRequest.ProtoReflect.Descriptor instead.
func (*GetVoiceChannelBindingRequest) Descriptor() ([]byte, []int) {
	return file_api_rtc_v1_query_proto_rawDescGZIP(), []int{6}
}

func (x *GetVoiceChannelBindingRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *GetVoiceChannelBindingRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type GetVoiceChannelBindingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Binding       *VoiceChannelBinding   `protobuf:"bytes,1,opt,name=binding,proto3" json:"binding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVoiceChannelBindingResponse) Reset() {
	*x = GetVoiceChannelBindingResponse{}
	mi := &file_api_rtc_v1_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVoiceChannelBindingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVoiceChannelBindingResponse) ProtoMessage() {}

func (x *GetVoiceChannelBindingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtc_v1_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVoiceChannelBindingResponse.ProtoReflect.Descriptor instead.
func (*GetVoiceChannelBindingResponse) Descriptor() ([]byte, []int) {
	return file_api_rtc_v1_query_proto_rawDescGZIP(), []int{7}
}

func (x *GetVoiceChannelBindingResponse) GetBinding() *VoiceChannelBinding {
	if x != nil {
		return x.Binding
	}
	return nil
}

type VoiceChannelBinding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	ChannelId     string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoiceChannelBinding) Reset() {
	*x = VoiceChannelBinding{}
	mi := &file_api_rtc_v1_query_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoiceChannelBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoiceChannelBinding) ProtoMessage() {}

func (x *VoiceChannelBinding) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtc_v1_query_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoiceChannelBinding.ProtoReflect.Descriptor instead.
func (*VoiceChannelBinding) Descriptor() ([]byte, []int) {
	return file_api_rtc_v1_query_proto_rawDescGZIP(), []int{8}
}

func (x *VoiceChannelBinding) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *VoiceChannelBinding) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *VoiceChannelBinding) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *VoiceChannelBinding) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetRtcTokenGrantStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       string                 `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRtcTokenGrantStatusRequest) Reset() {
	*x = GetRtcTokenGrantStatusRequest{}
	mi := &file_api_rtc_v1_query_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRtcTokenGrantStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRtcTokenGrantStatusRequest) ProtoMessage() {}

func (x *GetRtcTokenGrantStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtc_v1_query_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRtcTokenGrantStatusRequest.ProtoReflect.Descriptor instead.
func (*GetRtcTokenGrantStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_rtc_v1_query_proto_rawDescGZIP(), []int{9}
}

func (x *GetRtcTokenGrantStatusRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

type GetRtcTokenGrantStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *RtcTokenGrantStatus   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRtcTokenGrantStatusResponse) Reset() {
	*x = GetRtcTokenGrantStatusResponse{}
	mi := &file_api_rtc_v1_query_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRtcTokenGrantStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRtcTokenGrantStatusResponse) ProtoMessage() {}

func (x *GetRtcTokenGrantStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtc_v1_query_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRtcTokenGrantStatusResponse.ProtoReflect.Descriptor instead.
func (*GetRtcTokenGrantStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_rtc_v1_query_proto_rawDescGZIP(), []int{10}
}

func (x *GetRtcTokenGrantStatusResponse) GetStatus() *RtcTokenGrantStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type RtcTokenGrantStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       string                 `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IssuedAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Expired       bool                   `protobuf:"varint,6,opt,name=expired,proto3" json:"expired,omitempty"`
	CanPublish    bool                   `protobuf:"varint,7,opt,name=can_publish,json=canPublish,proto3" json:"can_publish,omitempty"`
	CanSubscribe  bool                   `protobuf:"varint,8,opt,name=can_subscribe,json=canSubscribe,proto3" json:"can_subscribe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RtcTokenGrantStatus) Reset() {
	*x = RtcTokenGrantStatus{}
	mi := &file_api_rtc_v1_query_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RtcTokenGrantStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RtcTokenGrantStatus) ProtoMessage() {}

func (x *RtcTokenGrantStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_rtc_v1_query_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RtcTokenGrantStatus.ProtoReflect.Descriptor instead.
func (*RtcTokenGrantStatus) Descriptor() ([]byte, []int) {
	return file_api_rtc_v1_query_proto_rawDescGZIP(), []int{11}
}

func (x *RtcTokenGrantStatus) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *RtcTokenGrantStatus) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RtcTokenGrantStatus) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RtcTokenGrantStatus) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *RtcTokenGrantStatus) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *RtcTokenGrantStatus) GetExpired() bool {
	if x != nil {
		return x.Expired
	}
	return false
}

func (x *RtcTokenGrantStatus) GetCanPublish() bool {
	if x != nil {
		return x.CanPublish
	}
	return false
}

func (x *RtcTokenGrantStatus) GetCanSubscribe() bool {
	if x != nil {
		return x.CanSubscribe
	}
	return false
}

var File_api_rtc_v1_query_proto protoreflect.FileDescriptor

const file_api_rtc_v1_query_proto_rawDesc = "" +
	"\n" +
	"\x16api/rtc/v1/query.proto\x12\vmint.rtc.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\\\n" +
	"\x18GetVoiceRoomStateRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\"N\n" +
	"\x19GetVoiceRoomStateResponse\x121\n" +
	"\x05state\x18\x01 \x01(\v2\x1b.mint.rtc.v1.VoiceRoomStateR\x05state\"\xfd\x01\n" +
	"\x0eVoiceRoomState\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x03 \x01(\tR\tchannelId\x12\x16\n" +
	"\x06active\x18\x04 \x01(\bR\x06active\x12+\n" +
	"\x11participant_count\x18\x05 \x01(\x05R\x10participantCount\x12K\n" +
	"\x14last_state_change_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x11lastStateChangeAt\"7\n" +
	"\x1cListVoiceParticipantsRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"b\n" +
	"\x1dListVoiceParticipantsResponse\x12A\n" +
	"\fparticipants\x18\x01 \x03(\v2\x1d.mint.rtc.v1.VoiceParticipantR\fparticipants\"\xeb\x01\n" +
	"\x10VoiceParticipant\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x127\n" +
	"\tjoined_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bjoinedAt\x123\n" +
	"\aleft_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x06leftAt\x12)\n" +
	"\x10microphone_muted\x18\x04 \x01(\bR\x0fmicrophoneMuted\x12%\n" +
	"\x0ecamera_enabled\x18\x05 \x01(\bR\rcameraEnabled\"a\n" +
	"\x1dGetVoiceChannelBindingRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\"\\\n" +
	"\x1eGetVoiceChannelBindingResponse\x12:\n" +
	"\abinding\x18\x01 \x01(\v2 .mint.rtc.v1.VoiceChannelBindingR\abinding\"\xab\x01\n" +
	"\x13VoiceChannelBinding\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomId\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\":\n" +
	"\x1dGetRtcTokenGrantStatusRequest\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\tR\atokenId\"Z\n" +
	"\x1eGetRtcTokenGrantStatusResponse\x128\n" +
	"\x06status\x18\x01 \x01(\v2 .mint.rtc.v1.RtcTokenGrantStatusR\x06status\"\xb6\x02\n" +
	"\x13RtcTokenGrantStatus\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\tR\atokenId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x127\n" +
	"\tissued_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x18\n" +
	"\aexpired\x18\x06 \x01(\bR\aexpired\x12\x1f\n" +
	"\vcan_publish\x18\a \x01(\bR\n" +
	"canPublish\x12#\n" +
	"\rcan_subscribe\x18\b \x01(\bR\fcanSubscribe2\xcb\x03\n" +
	"\x0fRTCQueryService\x12b\n" +
	"\x11GetVoiceRoomState\x12%.mint.rtc.v1.GetVoiceRoomStateRequest\x1a&.mint.rtc.v1.GetVoiceRoomStateResponse\x12n\n" +
	"\x15ListVoiceParticipants\x12).mint.rtc.v1.ListVoiceParticipantsRequest\x1a*.mint.rtc.v1.ListVoiceParticipantsResponse\x12q\n" +
	"\x16GetVoiceChannelBinding\x12*.mint.rtc.v1.GetVoiceChannelBindingRequest\x1a+.mint.rtc.v1.GetVoiceChannelBindingResponse\x12q\n" +
	"\x16GetRtcTokenGrantStatus\x12*.mint.rtc.v1.GetRtcTokenGrantStatusRequest\x1a+.mint.rtc.v1.GetRtcTokenGrantStatusResponseB+Z)github.com/c4erries/mint/api/rtc/v1;rtcv1b\x06proto3"

var (
	file_api_rtc_v1_query_proto_rawDescOnce sync.Once
	file_api_rtc_v1_query_proto_rawDescData []byte
)

func file_api_rtc_v1_query_proto_rawDescGZIP() []byte {
	file_api_rtc_v1_query_proto_rawDescOnce.Do(func() {
		file_api_rtc_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_rtc_v1_query_proto_rawDesc), len(file_api_rtc_v1_query_proto_rawDesc)))
	})
	return file_api_rtc_v1_query_proto_rawDescData
}

var file_api_rtc_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_rtc_v1_query_proto_goTypes = []any{
	(*GetVoiceRoomStateRequest)(nil),       // 0: mint.rtc.v1.GetVoiceRoomStateRequest
	(*GetVoiceRoomStateResponse)(nil),      // 1: mint.rtc.v1.GetVoiceRoomStateResponse
	(*VoiceRoomState)(nil),                 // 2: mint.rtc.v1.VoiceRoomState
	(*ListVoiceParticipantsRequest)(nil),   // 3: mint.rtc.v1.ListVoiceParticipantsRequest
	(*ListVoiceParticipantsResponse)(nil),  // 4: mint.rtc.v1.ListVoiceParticipantsResponse
	(*VoiceParticipant)(nil),               // 5: mint.rtc.v1.VoiceParticipant
	(*GetVoiceChannelBindingRequest)(nil),  // 6: mint.rtc.v1.GetVoiceChannelBindingRequest
	(*GetVoiceChannelBindingResponse)(nil), // 7: mint.rtc.v1.GetVoiceChannelBindingResponse
	(*VoiceChannelBinding)(nil),            // 8: mint.rtc.v1.VoiceChannelBinding
	(*GetRtcTokenGrantStatusRequest)(nil),  // 9: mint.rtc.v1.GetRtcTokenGrantStatusRequest
	(*GetRtcTokenGrantStatusResponse)(nil), // 10: mint.rtc.v1.GetRtcTokenGrantStatusResponse
	(*RtcTokenGrantStatus)(nil),            // 11: mint.rtc.v1.RtcTokenGrantStatus
	(*timestamppb.Timestamp)(nil),          // 12: google.protobuf.Timestamp
}
var file_api_rtc_v1_query_proto_depIdxs = []int32{
	2,  // 0: mint.rtc.v1.GetVoiceRoomStateResponse.state:type_name -> mint.rtc.v1.VoiceRoomState
	12, // 1: mint.rtc.v1.VoiceRoomState.last_state_change_at:type_name -> google.protobuf.Timestamp
	5,  // 2: mint.rtc.v1.ListVoiceParticipantsResponse.participants:type_name -> mint.rtc.v1.VoiceParticipant
	12, // 3: mint.rtc.v1.VoiceParticipant.joined_at:type_name -> google.protobuf.Timestamp
	12, // 4: mint.rtc.v1.VoiceParticipant.left_at:type_name -> google.protobuf.Timestamp
	8,  // 5: mint.rtc.v1.GetVoiceChannelBindingResponse.binding:type_name -> mint.rtc.v1.VoiceChannelBinding
	12, // 6: mint.rtc.v1.VoiceChannelBinding.updated_at:type_name -> google.protobuf.Timestamp
	11, // 7: mint.rtc.v1.GetRtcTokenGrantStatusResponse.status:type_name -> mint.rtc.v1.RtcTokenGrantStatus
	12, // 8: mint.rtc.v1.RtcTokenGrantStatus.issued_at:type_name -> google.protobuf.Timestamp
	12, // 9: mint.rtc.v1.RtcTokenGrantStatus.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 10: mint.rtc.v1.RTCQueryService.GetVoiceRoomState:input_type -> mint.rtc.v1.GetVoiceRoomStateRequest
	3,  // 11: mint.rtc.v1.RTCQueryService.ListVoiceParticipants:input_type -> mint.rtc.v1.ListVoiceParticipantsRequest
	6,  // 12: mint.rtc.v1.RTCQueryService.GetVoiceChannelBinding:input_type -> mint.rtc.v1.GetVoiceChannelBindingRequest
	9,  // 13: mint.rtc.v1.RTCQueryService.GetRtcTokenGrantStatus:input_type -> mint.rtc.v1.GetRtcTokenGrantStatusRequest
	1,  // 14: mint.rtc.v1.RTCQueryService.GetVoiceRoomState:output_type -> mint.rtc.v1.GetVoiceRoomStateResponse
	4,  // 15: mint.rtc.v1.RTCQueryService.ListVoiceParticipants:output_type -> mint.rtc.v1.ListVoiceParticipantsResponse
	7,  // 16: mint.rtc.v1.RTCQueryService.GetVoiceChannelBinding:output_type -> mint.rtc.v1.GetVoiceChannelBindingResponse
	10, // 17: mint.rtc.v1.RTCQueryService.GetRtcTokenGrantStatus:output_type -> mint.rtc.v1.GetRtcTokenGrantStatusResponse
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_api_rtc_v1_query_proto_init() }
func file_api_rtc_v1_query_proto_init() {
	if File_api_rtc_v1_query_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_rtc_v1_query_proto_rawDesc), len(file_api_rtc_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_rtc_v1_query_proto_goTypes,
		DependencyIndexes: file_api_rtc_v1_query_proto_depIdxs,
		MessageInfos:      file_api_rtc_v1_query_proto_msgTypes,
	}.Build()
	File_api_rtc_v1_query_proto = out.File
	file_api_rtc_v1_query_proto_goTypes = nil
	file_api_rtc_v1_query_proto_depIdxs = nil
}
