// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: api/rtc/v1/query.proto

package rtcv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RTCQueryService_GetVoiceRoomState_FullMethodName      = "/mint.rtc.v1.RTCQueryService/GetVoiceRoomState"
	RTCQueryService_ListVoiceParticipants_FullMethodName  = "/mint.rtc.v1.RTCQueryService/ListVoiceParticipants"
	RTCQueryService_GetVoiceChannelBinding_FullMethodName = "/mint.rtc.v1.RTCQueryService/GetVoiceChannelBinding"
	RTCQueryService_GetRtcTokenGrantStatus_FullMethodName = "/mint.rtc.v1.RTCQueryService/GetRtcTokenGrantStatus"
)

// RTCQueryServiceClient is the client API for RTCQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RTCQueryServiceClient interface {
	GetVoiceRoomState(ctx context.Context, in *GetVoiceRoomStateRequest, opts ...grpc.CallOption) (*GetVoiceRoomStateResponse, error)
	ListVoiceParticipants(ctx context.Context, in *ListVoiceParticipantsRequest, opts ...grpc.CallOption) (*ListVoiceParticipantsResponse, error)
	GetVoiceChannelBinding(ctx context.Context, in *GetVoiceChannelBindingRequest, opts ...grpc.CallOption) (*GetVoiceChannelBindingResponse, error)
	GetRtcTokenGrantStatus(ctx context.Context, in *GetRtcTokenGrantStatusRequest, opts ...grpc.CallOption) (*GetRtcTokenGrantStatusResponse, error)
}

type rTCQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRTCQueryServiceClient(cc grpc.ClientConnInterface) RTCQueryServiceClient {
	return &rTCQueryServiceClient{cc}
}

func (c *rTCQueryServiceClient) GetVoiceRoomState(ctx context.Context, in *GetVoiceRoomStateRequest, opts ...grpc.CallOption) (*GetVoiceRoomStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVoiceRoomStateResponse)
	err := c.cc.Invoke(ctx, RTCQueryService_GetVoiceRoomState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rTCQueryServiceClient) ListVoiceParticipants(ctx context.Context, in *ListVoiceParticipantsRequest, opts ...grpc.CallOption) (*ListVoiceParticipantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVoiceParticipantsResponse)
	err := c.cc.Invoke(ctx, RTCQueryService_ListVoiceParticipants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rTCQueryServiceClient) GetVoiceChannelBinding(ctx context.Context, in *GetVoiceChannelBindingRequest, opts ...grpc.CallOption) (*GetVoiceChannelBindingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVoiceChannelBindingResponse)
	err := c.cc.Invoke(ctx, RTCQueryService_GetVoiceChannelBinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rTCQueryServiceClient) GetRtcTokenGrantStatus(ctx context.Context, in *GetRtcTokenGrantStatusRequest, opts ...grpc.CallOption) (*GetRtcTokenGrantStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRtcTokenGrantStatusResponse)
	err := c.cc.Invoke(ctx, RTCQueryService_GetRtcTokenGrantStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RTCQueryServiceServer is the server API for RTCQueryService service.
// All implementations must embed UnimplementedRTCQueryServiceServer
// for forward compatibility.
type RTCQueryServiceServer interface {
	GetVoiceRoomState(context.Context, *GetVoiceRoomStateRequest) (*GetVoiceRoomStateResponse, error)
	ListVoiceParticipants(context.Context, *ListVoiceParticipantsRequest) (*ListVoiceParticipantsResponse, error)
	GetVoiceChannelBinding(context.Context, *GetVoiceChannelBindingRequest) (*GetVoiceChannelBindingResponse, error)
	GetRtcTokenGrantStatus(context.Context, *GetRtcTokenGrantStatusRequest) (*GetRtcTokenGrantStatusResponse, error)
	mustEmbedUnimplementedRTCQueryServiceServer()
}

// UnimplementedRTCQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRTCQueryServiceServer struct{}

func (UnimplementedRTCQueryServiceServer) GetVoiceRoomState(context.Context, *GetVoiceRoomStateRequest) (*GetVoiceRoomStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVoiceRoomState not implemented")
}
func (UnimplementedRTCQueryServiceServer) ListVoiceParticipants(context.Context, *ListVoiceParticipantsRequest) (*ListVoiceParticipantsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVoiceParticipants not implemented")
}
func (UnimplementedRTCQueryServiceServer) GetVoiceChannelBinding(context.Context, *GetVoiceChannelBindingRequest) (*GetVoiceChannelBindingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVoiceChannelBinding not implemented")
}
func (UnimplementedRTCQueryServiceServer) GetRtcTokenGrantStatus(context.Context, *GetRtcTokenGrantStatusRequest) (*GetRtcTokenGrantStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRtcTokenGrantStatus not implemented")
}
func (UnimplementedRTCQueryServiceServer) mustEmbedUnimplementedRTCQueryServiceServer() {}
func (UnimplementedRTCQueryServiceServer) testEmbeddedByValue()                         {}

// UnsafeRTCQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RTCQueryServiceServer will
// result in compilation errors.
type UnsafeRTCQueryServiceServer interface {
	mustEmbedUnimplementedRTCQueryServiceServer()
}

func RegisterRTCQueryServiceServer(s grpc.ServiceRegistrar, srv RTCQueryServiceServer) {
	// If the following call panics, it indicates UnimplementedRTCQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RTCQueryService_ServiceDesc, srv)
}

func _RTCQueryService_GetVoiceRoomState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVoiceRoomStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RTCQueryServiceServer).GetVoiceRoomState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RTCQueryService_GetVoiceRoomState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RTCQueryServiceServer).GetVoiceRoomState(ctx, req.(*GetVoiceRoomStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RTCQueryService_ListVoiceParticipants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVoiceParticipantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RTCQueryServiceServer).ListVoiceParticipants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RTCQueryService_ListVoiceParticipants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RTCQueryServiceServer).ListVoiceParticipants(ctx, req.(*ListVoiceParticipantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RTCQueryService_GetVoiceChannelBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVoiceChannelBindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RTCQueryServiceServer).GetVoiceChannelBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RTCQueryService_GetVoiceChannelBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RTCQueryServiceServer).GetVoiceChannelBinding(ctx, req.(*GetVoiceChannelBindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RTCQueryService_GetRtcTokenGrantStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRtcTokenGrantStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RTCQueryServiceServer).GetRtcTokenGrantStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RTCQueryService_GetRtcTokenGrantStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RTCQueryServiceServer).GetRtcTokenGrantStatus(ctx, req.(*GetRtcTokenGrantStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RTCQueryService_ServiceDesc is the grpc.ServiceDesc for RTCQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RTCQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mint.rtc.v1.RTCQueryService",
	HandlerType: (*RTCQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVoiceRoomState",
			Handler:    _RTCQueryService_GetVoiceRoomState_Handler,
		},
		{
			MethodName: "ListVoiceParticipants",
			Handler:    _RTCQueryService_ListVoiceParticipants_Handler,
		},
		{
			MethodName: "GetVoiceChannelBinding",
			Handler:    _RTCQueryService_GetVoiceChannelBinding_Handler,
		},
		{
			MethodName: "GetRtcTokenGrantStatus",
			Handler:    _RTCQueryService_GetRtcTokenGrantStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/rtc/v1/query.proto",
}
