// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	application "github.com/c4erries/mint/internal/workspace/application"

	mock "github.com/stretchr/testify/mock"
)

// OutboxStore is an autogenerated mock type for the OutboxStore type
type OutboxStore struct {
	mock.Mock
}

type OutboxStore_Expecter struct {
	mock *mock.Mock
}

func (_m *OutboxStore) EXPECT() *OutboxStore_Expecter {
	return &OutboxStore_Expecter{mock: &_m.Mock}
}

// ListUnpublished provides a mock function with given fields: ctx, limit
func (_m *OutboxStore) ListUnpublished(ctx context.Context, limit int) ([]application.OutboxMessage, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListUnpublished")
	}

	var r0 []application.OutboxMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]application.OutboxMessage, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []application.OutboxMessage); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]application.OutboxMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OutboxStore_ListUnpublished_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUnpublished'
type OutboxStore_ListUnpublished_Call struct {
	*mock.Call
}

// ListUnpublished is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *OutboxStore_Expecter) ListUnpublished(ctx interface{}, limit interface{}) *OutboxStore_ListUnpublished_Call {
	return &OutboxStore_ListUnpublished_Call{Call: _e.mock.On("ListUnpublished", ctx, limit)}
}

func (_c *OutboxStore_ListUnpublished_Call) Run(run func(ctx context.Context, limit int)) *OutboxStore_ListUnpublished_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *OutboxStore_ListUnpublished_Call) Return(_a0 []application.OutboxMessage, _a1 error) *OutboxStore_ListUnpublished_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OutboxStore_ListUnpublished_Call) RunAndReturn(run func(context.Context, int) ([]application.OutboxMessage, error)) *OutboxStore_ListUnpublished_Call {
	_c.Call.Return(run)
	return _c
}

// MarkPublished provides a mock function with given fields: ctx, eventID
func (_m *OutboxStore) MarkPublished(ctx context.Context, eventID string) error {
	ret := _m.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for MarkPublished")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, eventID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OutboxStore_MarkPublished_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkPublished'
type OutboxStore_MarkPublished_Call struct {
	*mock.Call
}

// MarkPublished is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID string
func (_e *OutboxStore_Expecter) MarkPublished(ctx interface{}, eventID interface{}) *OutboxStore_MarkPublished_Call {
	return &OutboxStore_MarkPublished_Call{Call: _e.mock.On("MarkPublished", ctx, eventID)}
}

func (_c *OutboxStore_MarkPublished_Call) Run(run func(ctx context.Context, eventID string)) *OutboxStore_MarkPublished_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *OutboxStore_MarkPublished_Call) Return(_a0 error) *OutboxStore_MarkPublished_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OutboxStore_MarkPublished_Call) RunAndReturn(run func(context.Context, string) error) *OutboxStore_MarkPublished_Call {
	_c.Call.Return(run)
	return _c
}

// NewOutboxStore creates a new instance of OutboxStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOutboxStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *OutboxStore {
	mock := &OutboxStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
