// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/c4erries/mint/internal/workspace/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewPermissionEvaluator creates a new instance of PermissionEvaluator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPermissionEvaluator(t interface {
	mock.TestingT
	Cleanup(func())
}) *PermissionEvaluator {
	mock := &PermissionEvaluator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PermissionEvaluator is an autogenerated mock type for the PermissionEvaluator type
type PermissionEvaluator struct {
	mock.Mock
}

type PermissionEvaluator_Expecter struct {
	mock *mock.Mock
}

func (_m *PermissionEvaluator) EXPECT() *PermissionEvaluator_Expecter {
	return &PermissionEvaluator_Expecter{mock: &_m.Mock}
}

// CanJoinVoiceChannel provides a mock function for the type PermissionEvaluator
func (_mock *PermissionEvaluator) CanJoinVoiceChannel(snapshot domain.PermissionSnapshot, userID string) (bool, error) {
	ret := _mock.Called(snapshot, userID)

	if len(ret) == 0 {
		panic("no return value specified for CanJoinVoiceChannel")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(domain.PermissionSnapshot, string) (bool, error)); ok {
		return returnFunc(snapshot, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(domain.PermissionSnapshot, string) bool); ok {
		r0 = returnFunc(snapshot, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(domain.PermissionSnapshot, string) error); ok {
		r1 = returnFunc(snapshot, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PermissionEvaluator_CanJoinVoiceChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanJoinVoiceChannel'
type PermissionEvaluator_CanJoinVoiceChannel_Call struct {
	*mock.Call
}

// CanJoinVoiceChannel is a helper method to define mock.On call
//   - snapshot domain.PermissionSnapshot
//   - userID string
func (_e *PermissionEvaluator_Expecter) CanJoinVoiceChannel(snapshot interface{}, userID interface{}) *PermissionEvaluator_CanJoinVoiceChannel_Call {
	return &PermissionEvaluator_CanJoinVoiceChannel_Call{Call: _e.mock.On("CanJoinVoiceChannel", snapshot, userID)}
}

func (_c *PermissionEvaluator_CanJoinVoiceChannel_Call) Run(run func(snapshot domain.PermissionSnapshot, userID string)) *PermissionEvaluator_CanJoinVoiceChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.PermissionSnapshot
		if args[0] != nil {
			arg0 = args[0].(domain.PermissionSnapshot)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PermissionEvaluator_CanJoinVoiceChannel_Call) Return(b bool, err error) *PermissionEvaluator_CanJoinVoiceChannel_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *PermissionEvaluator_CanJoinVoiceChannel_Call) RunAndReturn(run func(snapshot domain.PermissionSnapshot, userID string) (bool, error)) *PermissionEvaluator_CanJoinVoiceChannel_Call {
	_c.Call.Return(run)
	return _c
}
