// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	application "github.com/c4erries/mint/internal/workspace/application"

	domain "github.com/c4erries/mint/internal/workspace/domain"

	mock "github.com/stretchr/testify/mock"
)

// ReadRepository is an autogenerated mock type for the ReadRepository type
type ReadRepository struct {
	mock.Mock
}

type ReadRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ReadRepository) EXPECT() *ReadRepository_Expecter {
	return &ReadRepository_Expecter{mock: &_m.Mock}
}

// GetChannel provides a mock function with given fields: ctx, workspaceID, channelID
func (_m *ReadRepository) GetChannel(ctx context.Context, workspaceID string, channelID string) (application.ChannelView, error) {
	ret := _m.Called(ctx, workspaceID, channelID)

	if len(ret) == 0 {
		panic("no return value specified for GetChannel")
	}

	var r0 application.ChannelView
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (application.ChannelView, error)); ok {
		return rf(ctx, workspaceID, channelID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) application.ChannelView); ok {
		r0 = rf(ctx, workspaceID, channelID)
	} else {
		r0 = ret.Get(0).(application.ChannelView)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, workspaceID, channelID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadRepository_GetChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChannel'
type ReadRepository_GetChannel_Call struct {
	*mock.Call
}

// GetChannel is a helper method to define mock.On call
//   - ctx context.Context
//   - workspaceID string
//   - channelID string
func (_e *ReadRepository_Expecter) GetChannel(ctx interface{}, workspaceID interface{}, channelID interface{}) *ReadRepository_GetChannel_Call {
	return &ReadRepository_GetChannel_Call{Call: _e.mock.On("GetChannel", ctx, workspaceID, channelID)}
}

func (_c *ReadRepository_GetChannel_Call) Run(run func(ctx context.Context, workspaceID string, channelID string)) *ReadRepository_GetChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ReadRepository_GetChannel_Call) Return(_a0 application.ChannelView, _a1 error) *ReadRepository_GetChannel_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReadRepository_GetChannel_Call) RunAndReturn(run func(context.Context, string, string) (application.ChannelView, error)) *ReadRepository_GetChannel_Call {
	_c.Call.Return(run)
	return _c
}

// GetPermissionSnapshot provides a mock function with given fields: ctx, workspaceID, channelID
func (_m *ReadRepository) GetPermissionSnapshot(ctx context.Context, workspaceID string, channelID string) (domain.PermissionSnapshot, error) {
	ret := _m.Called(ctx, workspaceID, channelID)

	if len(ret) == 0 {
		panic("no return value specified for GetPermissionSnapshot")
	}

	var r0 domain.PermissionSnapshot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (domain.PermissionSnapshot, error)); ok {
		return rf(ctx, workspaceID, channelID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) domain.PermissionSnapshot); ok {
		r0 = rf(ctx, workspaceID, channelID)
	} else {
		r0 = ret.Get(0).(domain.PermissionSnapshot)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, workspaceID, channelID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadRepository_GetPermissionSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPermissionSnapshot'
type ReadRepository_GetPermissionSnapshot_Call struct {
	*mock.Call
}

// GetPermissionSnapshot is a helper method to define mock.On call
//   - ctx context.Context
//   - workspaceID string
//   - channelID string
func (_e *ReadRepository_Expecter) GetPermissionSnapshot(ctx interface{}, workspaceID interface{}, channelID interface{}) *ReadRepository_GetPermissionSnapshot_Call {
	return &ReadRepository_GetPermissionSnapshot_Call{Call: _e.mock.On("GetPermissionSnapshot", ctx, workspaceID, channelID)}
}

func (_c *ReadRepository_GetPermissionSnapshot_Call) Run(run func(ctx context.Context, workspaceID string, channelID string)) *ReadRepository_GetPermissionSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ReadRepository_GetPermissionSnapshot_Call) Return(_a0 domain.PermissionSnapshot, _a1 error) *ReadRepository_GetPermissionSnapshot_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReadRepository_GetPermissionSnapshot_Call) RunAndReturn(run func(context.Context, string, string) (domain.PermissionSnapshot, error)) *ReadRepository_GetPermissionSnapshot_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkspace provides a mock function with given fields: ctx, workspaceID
func (_m *ReadRepository) GetWorkspace(ctx context.Context, workspaceID string) (application.WorkspaceView, error) {
	ret := _m.Called(ctx, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkspace")
	}

	var r0 application.WorkspaceView
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (application.WorkspaceView, error)); ok {
		return rf(ctx, workspaceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) application.WorkspaceView); ok {
		r0 = rf(ctx, workspaceID)
	} else {
		r0 = ret.Get(0).(application.WorkspaceView)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, workspaceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadRepository_GetWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkspace'
type ReadRepository_GetWorkspace_Call struct {
	*mock.Call
}

// GetWorkspace is a helper method to define mock.On call
//   - ctx context.Context
//   - workspaceID string
func (_e *ReadRepository_Expecter) GetWorkspace(ctx interface{}, workspaceID interface{}) *ReadRepository_GetWorkspace_Call {
	return &ReadRepository_GetWorkspace_Call{Call: _e.mock.On("GetWorkspace", ctx, workspaceID)}
}

func (_c *ReadRepository_GetWorkspace_Call) Run(run func(ctx context.Context, workspaceID string)) *ReadRepository_GetWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ReadRepository_GetWorkspace_Call) Return(_a0 application.WorkspaceView, _a1 error) *ReadRepository_GetWorkspace_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReadRepository_GetWorkspace_Call) RunAndReturn(run func(context.Context, string) (application.WorkspaceView, error)) *ReadRepository_GetWorkspace_Call {
	_c.Call.Return(run)
	return _c
}

// NewReadRepository creates a new instance of ReadRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReadRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReadRepository {
	mock := &ReadRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
