// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	application "github.com/c4erries/mint/internal/workspace/application"

	mock "github.com/stretchr/testify/mock"
)

// WriteRepository is an autogenerated mock type for the WriteRepository type
type WriteRepository struct {
	mock.Mock
}

type WriteRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *WriteRepository) EXPECT() *WriteRepository_Expecter {
	return &WriteRepository_Expecter{mock: &_m.Mock}
}

// WithTx provides a mock function with given fields: ctx, fn
func (_m *WriteRepository) WithTx(ctx context.Context, fn func(application.WriteTx) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(application.WriteTx) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WriteRepository_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type WriteRepository_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(application.WriteTx) error
func (_e *WriteRepository_Expecter) WithTx(ctx interface{}, fn interface{}) *WriteRepository_WithTx_Call {
	return &WriteRepository_WithTx_Call{Call: _e.mock.On("WithTx", ctx, fn)}
}

func (_c *WriteRepository_WithTx_Call) Run(run func(ctx context.Context, fn func(application.WriteTx) error)) *WriteRepository_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(application.WriteTx) error))
	})
	return _c
}

func (_c *WriteRepository_WithTx_Call) Return(_a0 error) *WriteRepository_WithTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WriteRepository_WithTx_Call) RunAndReturn(run func(context.Context, func(application.WriteTx) error) error) *WriteRepository_WithTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewWriteRepository creates a new instance of WriteRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWriteRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *WriteRepository {
	mock := &WriteRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
