// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/c4erries/mint/internal/workspace/application"
	mock "github.com/stretchr/testify/mock"
)

// NewWriteRepository creates a new instance of WriteRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWriteRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *WriteRepository {
	mock := &WriteRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// WriteRepository is an autogenerated mock type for the WriteRepository type
type WriteRepository struct {
	mock.Mock
}

type WriteRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *WriteRepository) EXPECT() *WriteRepository_Expecter {
	return &WriteRepository_Expecter{mock: &_m.Mock}
}

// WithTx provides a mock function for the type WriteRepository
func (_mock *WriteRepository) WithTx(ctx context.Context, fn func(tx application.WriteTx) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(tx application.WriteTx) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WriteRepository_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type WriteRepository_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(tx application.WriteTx) error
func (_e *WriteRepository_Expecter) WithTx(ctx interface{}, fn interface{}) *WriteRepository_WithTx_Call {
	return &WriteRepository_WithTx_Call{Call: _e.mock.On("WithTx", ctx, fn)}
}

func (_c *WriteRepository_WithTx_Call) Run(run func(ctx context.Context, fn func(tx application.WriteTx) error)) *WriteRepository_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(tx application.WriteTx) error
		if args[1] != nil {
			arg1 = args[1].(func(tx application.WriteTx) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WriteRepository_WithTx_Call) Return(err error) *WriteRepository_WithTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WriteRepository_WithTx_Call) RunAndReturn(run func(ctx context.Context, fn func(tx application.WriteTx) error) error) *WriteRepository_WithTx_Call {
	_c.Call.Return(run)
	return _c
}
