// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/c4erries/mint/internal/workspace/application"
	"github.com/c4erries/mint/internal/workspace/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewWriteTx creates a new instance of WriteTx. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWriteTx(t interface {
	mock.TestingT
	Cleanup(func())
}) *WriteTx {
	mock := &WriteTx{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// WriteTx is an autogenerated mock type for the WriteTx type
type WriteTx struct {
	mock.Mock
}

type WriteTx_Expecter struct {
	mock *mock.Mock
}

func (_m *WriteTx) EXPECT() *WriteTx_Expecter {
	return &WriteTx_Expecter{mock: &_m.Mock}
}

// AppendOutbox provides a mock function for the type WriteTx
func (_mock *WriteTx) AppendOutbox(ctx context.Context, message application.OutboxMessage) error {
	ret := _mock.Called(ctx, message)

	if len(ret) == 0 {
		panic("no return value specified for AppendOutbox")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, application.OutboxMessage) error); ok {
		r0 = returnFunc(ctx, message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WriteTx_AppendOutbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppendOutbox'
type WriteTx_AppendOutbox_Call struct {
	*mock.Call
}

// AppendOutbox is a helper method to define mock.On call
//   - ctx context.Context
//   - message application.OutboxMessage
func (_e *WriteTx_Expecter) AppendOutbox(ctx interface{}, message interface{}) *WriteTx_AppendOutbox_Call {
	return &WriteTx_AppendOutbox_Call{Call: _e.mock.On("AppendOutbox", ctx, message)}
}

func (_c *WriteTx_AppendOutbox_Call) Run(run func(ctx context.Context, message application.OutboxMessage)) *WriteTx_AppendOutbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 application.OutboxMessage
		if args[1] != nil {
			arg1 = args[1].(application.OutboxMessage)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WriteTx_AppendOutbox_Call) Return(err error) *WriteTx_AppendOutbox_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WriteTx_AppendOutbox_Call) RunAndReturn(run func(ctx context.Context, message application.OutboxMessage) error) *WriteTx_AppendOutbox_Call {
	_c.Call.Return(run)
	return _c
}

// GetChannel provides a mock function for the type WriteTx
func (_mock *WriteTx) GetChannel(ctx context.Context, workspaceID string, channelID string) (domain.Channel, error) {
	ret := _mock.Called(ctx, workspaceID, channelID)

	if len(ret) == 0 {
		panic("no return value specified for GetChannel")
	}

	var r0 domain.Channel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (domain.Channel, error)); ok {
		return returnFunc(ctx, workspaceID, channelID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) domain.Channel); ok {
		r0 = returnFunc(ctx, workspaceID, channelID)
	} else {
		r0 = ret.Get(0).(domain.Channel)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, workspaceID, channelID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WriteTx_GetChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChannel'
type WriteTx_GetChannel_Call struct {
	*mock.Call
}

// GetChannel is a helper method to define mock.On call
//   - ctx context.Context
//   - workspaceID string
//   - channelID string
func (_e *WriteTx_Expecter) GetChannel(ctx interface{}, workspaceID interface{}, channelID interface{}) *WriteTx_GetChannel_Call {
	return &WriteTx_GetChannel_Call{Call: _e.mock.On("GetChannel", ctx, workspaceID, channelID)}
}

func (_c *WriteTx_GetChannel_Call) Run(run func(ctx context.Context, workspaceID string, channelID string)) *WriteTx_GetChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *WriteTx_GetChannel_Call) Return(channel domain.Channel, err error) *WriteTx_GetChannel_Call {
	_c.Call.Return(channel, err)
	return _c
}

func (_c *WriteTx_GetChannel_Call) RunAndReturn(run func(ctx context.Context, workspaceID string, channelID string) (domain.Channel, error)) *WriteTx_GetChannel_Call {
	_c.Call.Return(run)
	return _c
}

// GetMember provides a mock function for the type WriteTx
func (_mock *WriteTx) GetMember(ctx context.Context, workspaceID string, userID string) (domain.Member, error) {
	ret := _mock.Called(ctx, workspaceID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetMember")
	}

	var r0 domain.Member
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (domain.Member, error)); ok {
		return returnFunc(ctx, workspaceID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) domain.Member); ok {
		r0 = returnFunc(ctx, workspaceID, userID)
	} else {
		r0 = ret.Get(0).(domain.Member)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, workspaceID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WriteTx_GetMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMember'
type WriteTx_GetMember_Call struct {
	*mock.Call
}

// GetMember is a helper method to define mock.On call
//   - ctx context.Context
//   - workspaceID string
//   - userID string
func (_e *WriteTx_Expecter) GetMember(ctx interface{}, workspaceID interface{}, userID interface{}) *WriteTx_GetMember_Call {
	return &WriteTx_GetMember_Call{Call: _e.mock.On("GetMember", ctx, workspaceID, userID)}
}

func (_c *WriteTx_GetMember_Call) Run(run func(ctx context.Context, workspaceID string, userID string)) *WriteTx_GetMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *WriteTx_GetMember_Call) Return(member domain.Member, err error) *WriteTx_GetMember_Call {
	_c.Call.Return(member, err)
	return _c
}

func (_c *WriteTx_GetMember_Call) RunAndReturn(run func(ctx context.Context, workspaceID string, userID string) (domain.Member, error)) *WriteTx_GetMember_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkspace provides a mock function for the type WriteTx
func (_mock *WriteTx) GetWorkspace(ctx context.Context, workspaceID string) (domain.Workspace, error) {
	ret := _mock.Called(ctx, workspaceID)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkspace")
	}

	var r0 domain.Workspace
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.Workspace, error)); ok {
		return returnFunc(ctx, workspaceID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.Workspace); ok {
		r0 = returnFunc(ctx, workspaceID)
	} else {
		r0 = ret.Get(0).(domain.Workspace)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, workspaceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WriteTx_GetWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkspace'
type WriteTx_GetWorkspace_Call struct {
	*mock.Call
}

// GetWorkspace is a helper method to define mock.On call
//   - ctx context.Context
//   - workspaceID string
func (_e *WriteTx_Expecter) GetWorkspace(ctx interface{}, workspaceID interface{}) *WriteTx_GetWorkspace_Call {
	return &WriteTx_GetWorkspace_Call{Call: _e.mock.On("GetWorkspace", ctx, workspaceID)}
}

func (_c *WriteTx_GetWorkspace_Call) Run(run func(ctx context.Context, workspaceID string)) *WriteTx_GetWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WriteTx_GetWorkspace_Call) Return(workspace domain.Workspace, err error) *WriteTx_GetWorkspace_Call {
	_c.Call.Return(workspace, err)
	return _c
}

func (_c *WriteTx_GetWorkspace_Call) RunAndReturn(run func(ctx context.Context, workspaceID string) (domain.Workspace, error)) *WriteTx_GetWorkspace_Call {
	_c.Call.Return(run)
	return _c
}

// IsCommandProcessed provides a mock function for the type WriteTx
func (_mock *WriteTx) IsCommandProcessed(ctx context.Context, commandID string) (bool, error) {
	ret := _mock.Called(ctx, commandID)

	if len(ret) == 0 {
		panic("no return value specified for IsCommandProcessed")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, commandID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, commandID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, commandID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WriteTx_IsCommandProcessed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsCommandProcessed'
type WriteTx_IsCommandProcessed_Call struct {
	*mock.Call
}

// IsCommandProcessed is a helper method to define mock.On call
//   - ctx context.Context
//   - commandID string
func (_e *WriteTx_Expecter) IsCommandProcessed(ctx interface{}, commandID interface{}) *WriteTx_IsCommandProcessed_Call {
	return &WriteTx_IsCommandProcessed_Call{Call: _e.mock.On("IsCommandProcessed", ctx, commandID)}
}

func (_c *WriteTx_IsCommandProcessed_Call) Run(run func(ctx context.Context, commandID string)) *WriteTx_IsCommandProcessed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WriteTx_IsCommandProcessed_Call) Return(b bool, err error) *WriteTx_IsCommandProcessed_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *WriteTx_IsCommandProcessed_Call) RunAndReturn(run func(ctx context.Context, commandID string) (bool, error)) *WriteTx_IsCommandProcessed_Call {
	_c.Call.Return(run)
	return _c
}

// MarkCommandProcessed provides a mock function for the type WriteTx
func (_mock *WriteTx) MarkCommandProcessed(ctx context.Context, commandID string) error {
	ret := _mock.Called(ctx, commandID)

	if len(ret) == 0 {
		panic("no return value specified for MarkCommandProcessed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, commandID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WriteTx_MarkCommandProcessed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkCommandProcessed'
type WriteTx_MarkCommandProcessed_Call struct {
	*mock.Call
}

// MarkCommandProcessed is a helper method to define mock.On call
//   - ctx context.Context
//   - commandID string
func (_e *WriteTx_Expecter) MarkCommandProcessed(ctx interface{}, commandID interface{}) *WriteTx_MarkCommandProcessed_Call {
	return &WriteTx_MarkCommandProcessed_Call{Call: _e.mock.On("MarkCommandProcessed", ctx, commandID)}
}

func (_c *WriteTx_MarkCommandProcessed_Call) Run(run func(ctx context.Context, commandID string)) *WriteTx_MarkCommandProcessed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WriteTx_MarkCommandProcessed_Call) Return(err error) *WriteTx_MarkCommandProcessed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WriteTx_MarkCommandProcessed_Call) RunAndReturn(run func(ctx context.Context, commandID string) error) *WriteTx_MarkCommandProcessed_Call {
	_c.Call.Return(run)
	return _c
}

// SaveChannel provides a mock function for the type WriteTx
func (_mock *WriteTx) SaveChannel(ctx context.Context, channel domain.Channel) error {
	ret := _mock.Called(ctx, channel)

	if len(ret) == 0 {
		panic("no return value specified for SaveChannel")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Channel) error); ok {
		r0 = returnFunc(ctx, channel)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WriteTx_SaveChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveChannel'
type WriteTx_SaveChannel_Call struct {
	*mock.Call
}

// SaveChannel is a helper method to define mock.On call
//   - ctx context.Context
//   - channel domain.Channel
func (_e *WriteTx_Expecter) SaveChannel(ctx interface{}, channel interface{}) *WriteTx_SaveChannel_Call {
	return &WriteTx_SaveChannel_Call{Call: _e.mock.On("SaveChannel", ctx, channel)}
}

func (_c *WriteTx_SaveChannel_Call) Run(run func(ctx context.Context, channel domain.Channel)) *WriteTx_SaveChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Channel
		if args[1] != nil {
			arg1 = args[1].(domain.Channel)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WriteTx_SaveChannel_Call) Return(err error) *WriteTx_SaveChannel_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WriteTx_SaveChannel_Call) RunAndReturn(run func(ctx context.Context, channel domain.Channel) error) *WriteTx_SaveChannel_Call {
	_c.Call.Return(run)
	return _c
}

// SaveMember provides a mock function for the type WriteTx
func (_mock *WriteTx) SaveMember(ctx context.Context, member domain.Member) error {
	ret := _mock.Called(ctx, member)

	if len(ret) == 0 {
		panic("no return value specified for SaveMember")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Member) error); ok {
		r0 = returnFunc(ctx, member)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WriteTx_SaveMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveMember'
type WriteTx_SaveMember_Call struct {
	*mock.Call
}

// SaveMember is a helper method to define mock.On call
//   - ctx context.Context
//   - member domain.Member
func (_e *WriteTx_Expecter) SaveMember(ctx interface{}, member interface{}) *WriteTx_SaveMember_Call {
	return &WriteTx_SaveMember_Call{Call: _e.mock.On("SaveMember", ctx, member)}
}

func (_c *WriteTx_SaveMember_Call) Run(run func(ctx context.Context, member domain.Member)) *WriteTx_SaveMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Member
		if args[1] != nil {
			arg1 = args[1].(domain.Member)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WriteTx_SaveMember_Call) Return(err error) *WriteTx_SaveMember_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WriteTx_SaveMember_Call) RunAndReturn(run func(ctx context.Context, member domain.Member) error) *WriteTx_SaveMember_Call {
	_c.Call.Return(run)
	return _c
}

// SaveWorkspace provides a mock function for the type WriteTx
func (_mock *WriteTx) SaveWorkspace(ctx context.Context, workspace domain.Workspace) error {
	ret := _mock.Called(ctx, workspace)

	if len(ret) == 0 {
		panic("no return value specified for SaveWorkspace")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Workspace) error); ok {
		r0 = returnFunc(ctx, workspace)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WriteTx_SaveWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveWorkspace'
type WriteTx_SaveWorkspace_Call struct {
	*mock.Call
}

// SaveWorkspace is a helper method to define mock.On call
//   - ctx context.Context
//   - workspace domain.Workspace
func (_e *WriteTx_Expecter) SaveWorkspace(ctx interface{}, workspace interface{}) *WriteTx_SaveWorkspace_Call {
	return &WriteTx_SaveWorkspace_Call{Call: _e.mock.On("SaveWorkspace", ctx, workspace)}
}

func (_c *WriteTx_SaveWorkspace_Call) Run(run func(ctx context.Context, workspace domain.Workspace)) *WriteTx_SaveWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Workspace
		if args[1] != nil {
			arg1 = args[1].(domain.Workspace)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WriteTx_SaveWorkspace_Call) Return(err error) *WriteTx_SaveWorkspace_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WriteTx_SaveWorkspace_Call) RunAndReturn(run func(ctx context.Context, workspace domain.Workspace) error) *WriteTx_SaveWorkspace_Call {
	_c.Call.Return(run)
	return _c
}
