// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/c4erries/mint/internal/identity/domain"
	mock "github.com/stretchr/testify/mock"
)

// AccountRepository is an autogenerated mock type for the AccountRepository type
type AccountRepository struct {
	mock.Mock
}

type AccountRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *AccountRepository) EXPECT() *AccountRepository_Expecter {
	return &AccountRepository_Expecter{mock: &_m.Mock}
}

// CreateAccount provides a mock function with given fields: ctx, account
func (_m *AccountRepository) CreateAccount(ctx context.Context, account domain.Account) error {
	ret := _m.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Account) error); ok {
		r0 = rf(ctx, account)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AccountRepository_CreateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAccount'
type AccountRepository_CreateAccount_Call struct {
	*mock.Call
}

// CreateAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - account domain.Account
func (_e *AccountRepository_Expecter) CreateAccount(ctx interface{}, account interface{}) *AccountRepository_CreateAccount_Call {
	return &AccountRepository_CreateAccount_Call{Call: _e.mock.On("CreateAccount", ctx, account)}
}

func (_c *AccountRepository_CreateAccount_Call) Run(run func(ctx context.Context, account domain.Account)) *AccountRepository_CreateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Account))
	})
	return _c
}

func (_c *AccountRepository_CreateAccount_Call) Return(_a0 error) *AccountRepository_CreateAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AccountRepository_CreateAccount_Call) RunAndReturn(run func(context.Context, domain.Account) error) *AccountRepository_CreateAccount_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccountByEmail provides a mock function with given fields: ctx, email
func (_m *AccountRepository) GetAccountByEmail(ctx context.Context, email string) (domain.Account, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountByEmail")
	}

	var r0 domain.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Account, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Account); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(domain.Account)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AccountRepository_GetAccountByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountByEmail'
type AccountRepository_GetAccountByEmail_Call struct {
	*mock.Call
}

// GetAccountByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *AccountRepository_Expecter) GetAccountByEmail(ctx interface{}, email interface{}) *AccountRepository_GetAccountByEmail_Call {
	return &AccountRepository_GetAccountByEmail_Call{Call: _e.mock.On("GetAccountByEmail", ctx, email)}
}

func (_c *AccountRepository_GetAccountByEmail_Call) Run(run func(ctx context.Context, email string)) *AccountRepository_GetAccountByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *AccountRepository_GetAccountByEmail_Call) Return(_a0 domain.Account, _a1 error) *AccountRepository_GetAccountByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AccountRepository_GetAccountByEmail_Call) RunAndReturn(run func(context.Context, string) (domain.Account, error)) *AccountRepository_GetAccountByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccountByID provides a mock function with given fields: ctx, accountID
func (_m *AccountRepository) GetAccountByID(ctx context.Context, accountID string) (domain.Account, error) {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountByID")
	}

	var r0 domain.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Account, error)); ok {
		return rf(ctx, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Account); ok {
		r0 = rf(ctx, accountID)
	} else {
		r0 = ret.Get(0).(domain.Account)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AccountRepository_GetAccountByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountByID'
type AccountRepository_GetAccountByID_Call struct {
	*mock.Call
}

// GetAccountByID is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
func (_e *AccountRepository_Expecter) GetAccountByID(ctx interface{}, accountID interface{}) *AccountRepository_GetAccountByID_Call {
	return &AccountRepository_GetAccountByID_Call{Call: _e.mock.On("GetAccountByID", ctx, accountID)}
}

func (_c *AccountRepository_GetAccountByID_Call) Run(run func(ctx context.Context, accountID string)) *AccountRepository_GetAccountByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *AccountRepository_GetAccountByID_Call) Return(_a0 domain.Account, _a1 error) *AccountRepository_GetAccountByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AccountRepository_GetAccountByID_Call) RunAndReturn(run func(context.Context, string) (domain.Account, error)) *AccountRepository_GetAccountByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewAccountRepository creates a new instance of AccountRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountRepository {
	mock := &AccountRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
