// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// RevocationStore is an autogenerated mock type for the RevocationStore type
type RevocationStore struct {
	mock.Mock
}

type RevocationStore_Expecter struct {
	mock *mock.Mock
}

func (_m *RevocationStore) EXPECT() *RevocationStore_Expecter {
	return &RevocationStore_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *RevocationStore) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RevocationStore_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type RevocationStore_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *RevocationStore_Expecter) Close() *RevocationStore_Close_Call {
	return &RevocationStore_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *RevocationStore_Close_Call) Run(run func()) *RevocationStore_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RevocationStore_Close_Call) Return(_a0 error) *RevocationStore_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RevocationStore_Close_Call) RunAndReturn(run func() error) *RevocationStore_Close_Call {
	_c.Call.Return(run)
	return _c
}

// IsRevoked provides a mock function with given fields: ctx, tokenID
func (_m *RevocationStore) IsRevoked(ctx context.Context, tokenID string) (bool, error) {
	ret := _m.Called(ctx, tokenID)

	if len(ret) == 0 {
		panic("no return value specified for IsRevoked")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, tokenID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, tokenID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RevocationStore_IsRevoked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsRevoked'
type RevocationStore_IsRevoked_Call struct {
	*mock.Call
}

// IsRevoked is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenID string
func (_e *RevocationStore_Expecter) IsRevoked(ctx interface{}, tokenID interface{}) *RevocationStore_IsRevoked_Call {
	return &RevocationStore_IsRevoked_Call{Call: _e.mock.On("IsRevoked", ctx, tokenID)}
}

func (_c *RevocationStore_IsRevoked_Call) Run(run func(ctx context.Context, tokenID string)) *RevocationStore_IsRevoked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *RevocationStore_IsRevoked_Call) Return(_a0 bool, _a1 error) *RevocationStore_IsRevoked_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RevocationStore_IsRevoked_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *RevocationStore_IsRevoked_Call {
	_c.Call.Return(run)
	return _c
}

// MarkRevoked provides a mock function with given fields: ctx, tokenID, expiresAt
func (_m *RevocationStore) MarkRevoked(ctx context.Context, tokenID string, expiresAt time.Time) error {
	ret := _m.Called(ctx, tokenID, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for MarkRevoked")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = rf(ctx, tokenID, expiresAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RevocationStore_MarkRevoked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkRevoked'
type RevocationStore_MarkRevoked_Call struct {
	*mock.Call
}

// MarkRevoked is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenID string
//   - expiresAt time.Time
func (_e *RevocationStore_Expecter) MarkRevoked(ctx interface{}, tokenID interface{}, expiresAt interface{}) *RevocationStore_MarkRevoked_Call {
	return &RevocationStore_MarkRevoked_Call{Call: _e.mock.On("MarkRevoked", ctx, tokenID, expiresAt)}
}

func (_c *RevocationStore_MarkRevoked_Call) Run(run func(ctx context.Context, tokenID string, expiresAt time.Time)) *RevocationStore_MarkRevoked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time))
	})
	return _c
}

func (_c *RevocationStore_MarkRevoked_Call) Return(_a0 error) *RevocationStore_MarkRevoked_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RevocationStore_MarkRevoked_Call) RunAndReturn(run func(context.Context, string, time.Time) error) *RevocationStore_MarkRevoked_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function with given fields: ctx
func (_m *RevocationStore) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RevocationStore_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type RevocationStore_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *RevocationStore_Expecter) Ping(ctx interface{}) *RevocationStore_Ping_Call {
	return &RevocationStore_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *RevocationStore_Ping_Call) Run(run func(ctx context.Context)) *RevocationStore_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *RevocationStore_Ping_Call) Return(_a0 error) *RevocationStore_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RevocationStore_Ping_Call) RunAndReturn(run func(context.Context) error) *RevocationStore_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// NewRevocationStore creates a new instance of RevocationStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRevocationStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *RevocationStore {
	mock := &RevocationStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
