// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/c4erries/mint/internal/identity/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// SessionRepository is an autogenerated mock type for the SessionRepository type
type SessionRepository struct {
	mock.Mock
}

type SessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *SessionRepository) EXPECT() *SessionRepository_Expecter {
	return &SessionRepository_Expecter{mock: &_m.Mock}
}

// CreateSession provides a mock function with given fields: ctx, session
func (_m *SessionRepository) CreateSession(ctx context.Context, session domain.Session) error {
	ret := _m.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Session) error); ok {
		r0 = rf(ctx, session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SessionRepository_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type SessionRepository_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - session domain.Session
func (_e *SessionRepository_Expecter) CreateSession(ctx interface{}, session interface{}) *SessionRepository_CreateSession_Call {
	return &SessionRepository_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, session)}
}

func (_c *SessionRepository_CreateSession_Call) Run(run func(ctx context.Context, session domain.Session)) *SessionRepository_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Session))
	})
	return _c
}

func (_c *SessionRepository_CreateSession_Call) Return(_a0 error) *SessionRepository_CreateSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SessionRepository_CreateSession_Call) RunAndReturn(run func(context.Context, domain.Session) error) *SessionRepository_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetSessionByRefreshJTI provides a mock function with given fields: ctx, refreshJTI
func (_m *SessionRepository) GetSessionByRefreshJTI(ctx context.Context, refreshJTI string) (domain.Session, error) {
	ret := _m.Called(ctx, refreshJTI)

	if len(ret) == 0 {
		panic("no return value specified for GetSessionByRefreshJTI")
	}

	var r0 domain.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Session, error)); ok {
		return rf(ctx, refreshJTI)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Session); ok {
		r0 = rf(ctx, refreshJTI)
	} else {
		r0 = ret.Get(0).(domain.Session)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refreshJTI)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SessionRepository_GetSessionByRefreshJTI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSessionByRefreshJTI'
type SessionRepository_GetSessionByRefreshJTI_Call struct {
	*mock.Call
}

// GetSessionByRefreshJTI is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshJTI string
func (_e *SessionRepository_Expecter) GetSessionByRefreshJTI(ctx interface{}, refreshJTI interface{}) *SessionRepository_GetSessionByRefreshJTI_Call {
	return &SessionRepository_GetSessionByRefreshJTI_Call{Call: _e.mock.On("GetSessionByRefreshJTI", ctx, refreshJTI)}
}

func (_c *SessionRepository_GetSessionByRefreshJTI_Call) Run(run func(ctx context.Context, refreshJTI string)) *SessionRepository_GetSessionByRefreshJTI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *SessionRepository_GetSessionByRefreshJTI_Call) Return(_a0 domain.Session, _a1 error) *SessionRepository_GetSessionByRefreshJTI_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SessionRepository_GetSessionByRefreshJTI_Call) RunAndReturn(run func(context.Context, string) (domain.Session, error)) *SessionRepository_GetSessionByRefreshJTI_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeSession provides a mock function with given fields: ctx, sessionID, revokedAt
func (_m *SessionRepository) RevokeSession(ctx context.Context, sessionID string, revokedAt time.Time) error {
	ret := _m.Called(ctx, sessionID, revokedAt)

	if len(ret) == 0 {
		panic("no return value specified for RevokeSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = rf(ctx, sessionID, revokedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SessionRepository_RevokeSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeSession'
type SessionRepository_RevokeSession_Call struct {
	*mock.Call
}

// RevokeSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
//   - revokedAt time.Time
func (_e *SessionRepository_Expecter) RevokeSession(ctx interface{}, sessionID interface{}, revokedAt interface{}) *SessionRepository_RevokeSession_Call {
	return &SessionRepository_RevokeSession_Call{Call: _e.mock.On("RevokeSession", ctx, sessionID, revokedAt)}
}

func (_c *SessionRepository_RevokeSession_Call) Run(run func(ctx context.Context, sessionID string, revokedAt time.Time)) *SessionRepository_RevokeSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time))
	})
	return _c
}

func (_c *SessionRepository_RevokeSession_Call) Return(_a0 error) *SessionRepository_RevokeSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SessionRepository_RevokeSession_Call) RunAndReturn(run func(context.Context, string, time.Time) error) *SessionRepository_RevokeSession_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSessionRefresh provides a mock function with given fields: ctx, sessionID, oldRefreshJTI, newRefreshJTI, expiresAt
func (_m *SessionRepository) UpdateSessionRefresh(ctx context.Context, sessionID string, oldRefreshJTI string, newRefreshJTI string, expiresAt time.Time) error {
	ret := _m.Called(ctx, sessionID, oldRefreshJTI, newRefreshJTI, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSessionRefresh")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, time.Time) error); ok {
		r0 = rf(ctx, sessionID, oldRefreshJTI, newRefreshJTI, expiresAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SessionRepository_UpdateSessionRefresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSessionRefresh'
type SessionRepository_UpdateSessionRefresh_Call struct {
	*mock.Call
}

// UpdateSessionRefresh is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
//   - oldRefreshJTI string
//   - newRefreshJTI string
//   - expiresAt time.Time
func (_e *SessionRepository_Expecter) UpdateSessionRefresh(ctx interface{}, sessionID interface{}, oldRefreshJTI interface{}, newRefreshJTI interface{}, expiresAt interface{}) *SessionRepository_UpdateSessionRefresh_Call {
	return &SessionRepository_UpdateSessionRefresh_Call{Call: _e.mock.On("UpdateSessionRefresh", ctx, sessionID, oldRefreshJTI, newRefreshJTI, expiresAt)}
}

func (_c *SessionRepository_UpdateSessionRefresh_Call) Run(run func(ctx context.Context, sessionID string, oldRefreshJTI string, newRefreshJTI string, expiresAt time.Time)) *SessionRepository_UpdateSessionRefresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(time.Time))
	})
	return _c
}

func (_c *SessionRepository_UpdateSessionRefresh_Call) Return(_a0 error) *SessionRepository_UpdateSessionRefresh_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SessionRepository_UpdateSessionRefresh_Call) RunAndReturn(run func(context.Context, string, string, string, time.Time) error) *SessionRepository_UpdateSessionRefresh_Call {
	_c.Call.Return(run)
	return _c
}

// NewSessionRepository creates a new instance of SessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionRepository {
	mock := &SessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
