// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/c4erries/mint/internal/identity/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewSessionRepository creates a new instance of SessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionRepository {
	mock := &SessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SessionRepository is an autogenerated mock type for the SessionRepository type
type SessionRepository struct {
	mock.Mock
}

type SessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *SessionRepository) EXPECT() *SessionRepository_Expecter {
	return &SessionRepository_Expecter{mock: &_m.Mock}
}

// CreateSession provides a mock function for the type SessionRepository
func (_mock *SessionRepository) CreateSession(ctx context.Context, session domain.Session) error {
	ret := _mock.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Session) error); ok {
		r0 = returnFunc(ctx, session)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionRepository_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type SessionRepository_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - session domain.Session
func (_e *SessionRepository_Expecter) CreateSession(ctx interface{}, session interface{}) *SessionRepository_CreateSession_Call {
	return &SessionRepository_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, session)}
}

func (_c *SessionRepository_CreateSession_Call) Run(run func(ctx context.Context, session domain.Session)) *SessionRepository_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Session
		if args[1] != nil {
			arg1 = args[1].(domain.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionRepository_CreateSession_Call) Return(err error) *SessionRepository_CreateSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionRepository_CreateSession_Call) RunAndReturn(run func(ctx context.Context, session domain.Session) error) *SessionRepository_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetSessionByRefreshJTI provides a mock function for the type SessionRepository
func (_mock *SessionRepository) GetSessionByRefreshJTI(ctx context.Context, refreshJTI string) (domain.Session, error) {
	ret := _mock.Called(ctx, refreshJTI)

	if len(ret) == 0 {
		panic("no return value specified for GetSessionByRefreshJTI")
	}

	var r0 domain.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.Session, error)); ok {
		return returnFunc(ctx, refreshJTI)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.Session); ok {
		r0 = returnFunc(ctx, refreshJTI)
	} else {
		r0 = ret.Get(0).(domain.Session)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, refreshJTI)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SessionRepository_GetSessionByRefreshJTI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSessionByRefreshJTI'
type SessionRepository_GetSessionByRefreshJTI_Call struct {
	*mock.Call
}

// GetSessionByRefreshJTI is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshJTI string
func (_e *SessionRepository_Expecter) GetSessionByRefreshJTI(ctx interface{}, refreshJTI interface{}) *SessionRepository_GetSessionByRefreshJTI_Call {
	return &SessionRepository_GetSessionByRefreshJTI_Call{Call: _e.mock.On("GetSessionByRefreshJTI", ctx, refreshJTI)}
}

func (_c *SessionRepository_GetSessionByRefreshJTI_Call) Run(run func(ctx context.Context, refreshJTI string)) *SessionRepository_GetSessionByRefreshJTI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionRepository_GetSessionByRefreshJTI_Call) Return(session domain.Session, err error) *SessionRepository_GetSessionByRefreshJTI_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *SessionRepository_GetSessionByRefreshJTI_Call) RunAndReturn(run func(ctx context.Context, refreshJTI string) (domain.Session, error)) *SessionRepository_GetSessionByRefreshJTI_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeSession provides a mock function for the type SessionRepository
func (_mock *SessionRepository) RevokeSession(ctx context.Context, sessionID string, revokedAt time.Time) error {
	ret := _mock.Called(ctx, sessionID, revokedAt)

	if len(ret) == 0 {
		panic("no return value specified for RevokeSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = returnFunc(ctx, sessionID, revokedAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionRepository_RevokeSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeSession'
type SessionRepository_RevokeSession_Call struct {
	*mock.Call
}

// RevokeSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
//   - revokedAt time.Time
func (_e *SessionRepository_Expecter) RevokeSession(ctx interface{}, sessionID interface{}, revokedAt interface{}) *SessionRepository_RevokeSession_Call {
	return &SessionRepository_RevokeSession_Call{Call: _e.mock.On("RevokeSession", ctx, sessionID, revokedAt)}
}

func (_c *SessionRepository_RevokeSession_Call) Run(run func(ctx context.Context, sessionID string, revokedAt time.Time)) *SessionRepository_RevokeSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *SessionRepository_RevokeSession_Call) Return(err error) *SessionRepository_RevokeSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionRepository_RevokeSession_Call) RunAndReturn(run func(ctx context.Context, sessionID string, revokedAt time.Time) error) *SessionRepository_RevokeSession_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSessionRefresh provides a mock function for the type SessionRepository
func (_mock *SessionRepository) UpdateSessionRefresh(ctx context.Context, sessionID string, oldRefreshJTI string, newRefreshJTI string, expiresAt time.Time) error {
	ret := _mock.Called(ctx, sessionID, oldRefreshJTI, newRefreshJTI, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSessionRefresh")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, time.Time) error); ok {
		r0 = returnFunc(ctx, sessionID, oldRefreshJTI, newRefreshJTI, expiresAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionRepository_UpdateSessionRefresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSessionRefresh'
type SessionRepository_UpdateSessionRefresh_Call struct {
	*mock.Call
}

// UpdateSessionRefresh is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
//   - oldRefreshJTI string
//   - newRefreshJTI string
//   - expiresAt time.Time
func (_e *SessionRepository_Expecter) UpdateSessionRefresh(ctx interface{}, sessionID interface{}, oldRefreshJTI interface{}, newRefreshJTI interface{}, expiresAt interface{}) *SessionRepository_UpdateSessionRefresh_Call {
	return &SessionRepository_UpdateSessionRefresh_Call{Call: _e.mock.On("UpdateSessionRefresh", ctx, sessionID, oldRefreshJTI, newRefreshJTI, expiresAt)}
}

func (_c *SessionRepository_UpdateSessionRefresh_Call) Run(run func(ctx context.Context, sessionID string, oldRefreshJTI string, newRefreshJTI string, expiresAt time.Time)) *SessionRepository_UpdateSessionRefresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *SessionRepository_UpdateSessionRefresh_Call) Return(err error) *SessionRepository_UpdateSessionRefresh_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionRepository_UpdateSessionRefresh_Call) RunAndReturn(run func(ctx context.Context, sessionID string, oldRefreshJTI string, newRefreshJTI string, expiresAt time.Time) error) *SessionRepository_UpdateSessionRefresh_Call {
	_c.Call.Return(run)
	return _c
}
