// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	"github.com/c4erries/mint/internal/identity/application"
	mock "github.com/stretchr/testify/mock"
)

// NewTokenManager creates a new instance of TokenManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenManager {
	mock := &TokenManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TokenManager is an autogenerated mock type for the TokenManager type
type TokenManager struct {
	mock.Mock
}

type TokenManager_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenManager) EXPECT() *TokenManager_Expecter {
	return &TokenManager_Expecter{mock: &_m.Mock}
}

// IssueToken provides a mock function for the type TokenManager
func (_mock *TokenManager) IssueToken(accountID string, sessionID string, tokenType application.TokenType, ttl time.Duration, now time.Time) (application.IssuedToken, error) {
	ret := _mock.Called(accountID, sessionID, tokenType, ttl, now)

	if len(ret) == 0 {
		panic("no return value specified for IssueToken")
	}

	var r0 application.IssuedToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, application.TokenType, time.Duration, time.Time) (application.IssuedToken, error)); ok {
		return returnFunc(accountID, sessionID, tokenType, ttl, now)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, application.TokenType, time.Duration, time.Time) application.IssuedToken); ok {
		r0 = returnFunc(accountID, sessionID, tokenType, ttl, now)
	} else {
		r0 = ret.Get(0).(application.IssuedToken)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, application.TokenType, time.Duration, time.Time) error); ok {
		r1 = returnFunc(accountID, sessionID, tokenType, ttl, now)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenManager_IssueToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IssueToken'
type TokenManager_IssueToken_Call struct {
	*mock.Call
}

// IssueToken is a helper method to define mock.On call
//   - accountID string
//   - sessionID string
//   - tokenType application.TokenType
//   - ttl time.Duration
//   - now time.Time
func (_e *TokenManager_Expecter) IssueToken(accountID interface{}, sessionID interface{}, tokenType interface{}, ttl interface{}, now interface{}) *TokenManager_IssueToken_Call {
	return &TokenManager_IssueToken_Call{Call: _e.mock.On("IssueToken", accountID, sessionID, tokenType, ttl, now)}
}

func (_c *TokenManager_IssueToken_Call) Run(run func(accountID string, sessionID string, tokenType application.TokenType, ttl time.Duration, now time.Time)) *TokenManager_IssueToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 application.TokenType
		if args[2] != nil {
			arg2 = args[2].(application.TokenType)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *TokenManager_IssueToken_Call) Return(issuedToken application.IssuedToken, err error) *TokenManager_IssueToken_Call {
	_c.Call.Return(issuedToken, err)
	return _c
}

func (_c *TokenManager_IssueToken_Call) RunAndReturn(run func(accountID string, sessionID string, tokenType application.TokenType, ttl time.Duration, now time.Time) (application.IssuedToken, error)) *TokenManager_IssueToken_Call {
	_c.Call.Return(run)
	return _c
}

// ParseToken provides a mock function for the type TokenManager
func (_mock *TokenManager) ParseToken(rawToken string, expectedType application.TokenType) (application.TokenClaims, error) {
	ret := _mock.Called(rawToken, expectedType)

	if len(ret) == 0 {
		panic("no return value specified for ParseToken")
	}

	var r0 application.TokenClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, application.TokenType) (application.TokenClaims, error)); ok {
		return returnFunc(rawToken, expectedType)
	}
	if returnFunc, ok := ret.Get(0).(func(string, application.TokenType) application.TokenClaims); ok {
		r0 = returnFunc(rawToken, expectedType)
	} else {
		r0 = ret.Get(0).(application.TokenClaims)
	}
	if returnFunc, ok := ret.Get(1).(func(string, application.TokenType) error); ok {
		r1 = returnFunc(rawToken, expectedType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenManager_ParseToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseToken'
type TokenManager_ParseToken_Call struct {
	*mock.Call
}

// ParseToken is a helper method to define mock.On call
//   - rawToken string
//   - expectedType application.TokenType
func (_e *TokenManager_Expecter) ParseToken(rawToken interface{}, expectedType interface{}) *TokenManager_ParseToken_Call {
	return &TokenManager_ParseToken_Call{Call: _e.mock.On("ParseToken", rawToken, expectedType)}
}

func (_c *TokenManager_ParseToken_Call) Run(run func(rawToken string, expectedType application.TokenType)) *TokenManager_ParseToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 application.TokenType
		if args[1] != nil {
			arg1 = args[1].(application.TokenType)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TokenManager_ParseToken_Call) Return(tokenClaims application.TokenClaims, err error) *TokenManager_ParseToken_Call {
	_c.Call.Return(tokenClaims, err)
	return _c
}

func (_c *TokenManager_ParseToken_Call) RunAndReturn(run func(rawToken string, expectedType application.TokenType) (application.TokenClaims, error)) *TokenManager_ParseToken_Call {
	_c.Call.Return(run)
	return _c
}
