// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	application "github.com/c4erries/mint/internal/identity/application"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// TokenManager is an autogenerated mock type for the TokenManager type
type TokenManager struct {
	mock.Mock
}

type TokenManager_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenManager) EXPECT() *TokenManager_Expecter {
	return &TokenManager_Expecter{mock: &_m.Mock}
}

// IssueToken provides a mock function with given fields: accountID, sessionID, tokenType, ttl, now
func (_m *TokenManager) IssueToken(accountID string, sessionID string, tokenType application.TokenType, ttl time.Duration, now time.Time) (application.IssuedToken, error) {
	ret := _m.Called(accountID, sessionID, tokenType, ttl, now)

	if len(ret) == 0 {
		panic("no return value specified for IssueToken")
	}

	var r0 application.IssuedToken
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, application.TokenType, time.Duration, time.Time) (application.IssuedToken, error)); ok {
		return rf(accountID, sessionID, tokenType, ttl, now)
	}
	if rf, ok := ret.Get(0).(func(string, string, application.TokenType, time.Duration, time.Time) application.IssuedToken); ok {
		r0 = rf(accountID, sessionID, tokenType, ttl, now)
	} else {
		r0 = ret.Get(0).(application.IssuedToken)
	}

	if rf, ok := ret.Get(1).(func(string, string, application.TokenType, time.Duration, time.Time) error); ok {
		r1 = rf(accountID, sessionID, tokenType, ttl, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenManager_IssueToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IssueToken'
type TokenManager_IssueToken_Call struct {
	*mock.Call
}

// IssueToken is a helper method to define mock.On call
//   - accountID string
//   - sessionID string
//   - tokenType application.TokenType
//   - ttl time.Duration
//   - now time.Time
func (_e *TokenManager_Expecter) IssueToken(accountID interface{}, sessionID interface{}, tokenType interface{}, ttl interface{}, now interface{}) *TokenManager_IssueToken_Call {
	return &TokenManager_IssueToken_Call{Call: _e.mock.On("IssueToken", accountID, sessionID, tokenType, ttl, now)}
}

func (_c *TokenManager_IssueToken_Call) Run(run func(accountID string, sessionID string, tokenType application.TokenType, ttl time.Duration, now time.Time)) *TokenManager_IssueToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(application.TokenType), args[3].(time.Duration), args[4].(time.Time))
	})
	return _c
}

func (_c *TokenManager_IssueToken_Call) Return(_a0 application.IssuedToken, _a1 error) *TokenManager_IssueToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenManager_IssueToken_Call) RunAndReturn(run func(string, string, application.TokenType, time.Duration, time.Time) (application.IssuedToken, error)) *TokenManager_IssueToken_Call {
	_c.Call.Return(run)
	return _c
}

// ParseToken provides a mock function with given fields: rawToken, expectedType
func (_m *TokenManager) ParseToken(rawToken string, expectedType application.TokenType) (application.TokenClaims, error) {
	ret := _m.Called(rawToken, expectedType)

	if len(ret) == 0 {
		panic("no return value specified for ParseToken")
	}

	var r0 application.TokenClaims
	var r1 error
	if rf, ok := ret.Get(0).(func(string, application.TokenType) (application.TokenClaims, error)); ok {
		return rf(rawToken, expectedType)
	}
	if rf, ok := ret.Get(0).(func(string, application.TokenType) application.TokenClaims); ok {
		r0 = rf(rawToken, expectedType)
	} else {
		r0 = ret.Get(0).(application.TokenClaims)
	}

	if rf, ok := ret.Get(1).(func(string, application.TokenType) error); ok {
		r1 = rf(rawToken, expectedType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenManager_ParseToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseToken'
type TokenManager_ParseToken_Call struct {
	*mock.Call
}

// ParseToken is a helper method to define mock.On call
//   - rawToken string
//   - expectedType application.TokenType
func (_e *TokenManager_Expecter) ParseToken(rawToken interface{}, expectedType interface{}) *TokenManager_ParseToken_Call {
	return &TokenManager_ParseToken_Call{Call: _e.mock.On("ParseToken", rawToken, expectedType)}
}

func (_c *TokenManager_ParseToken_Call) Run(run func(rawToken string, expectedType application.TokenType)) *TokenManager_ParseToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(application.TokenType))
	})
	return _c
}

func (_c *TokenManager_ParseToken_Call) Return(_a0 application.TokenClaims, _a1 error) *TokenManager_ParseToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenManager_ParseToken_Call) RunAndReturn(run func(string, application.TokenType) (application.TokenClaims, error)) *TokenManager_ParseToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewTokenManager creates a new instance of TokenManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenManager {
	mock := &TokenManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
