// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/permission/v1/permission.proto

package permissionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CanJoinVoiceChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	ChannelId     string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanJoinVoiceChannelRequest) Reset() {
	*x = CanJoinVoiceChannelRequest{}
	mi := &file_api_permission_v1_permission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanJoinVoiceChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanJoinVoiceChannelRequest) ProtoMessage() {}

func (x *CanJoinVoiceChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_permission_v1_permission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanJoinVoiceChannelRequest.ProtoReflect.Descriptor instead.
func (*CanJoinVoiceChannelRequest) Descriptor() ([]byte, []int) {
	return file_api_permission_v1_permission_proto_rawDescGZIP(), []int{0}
}

func (x *CanJoinVoiceChannelRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *CanJoinVoiceChannelRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *CanJoinVoiceChannelRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CanJoinVoiceChannelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanJoinVoiceChannelResponse) Reset() {
	*x = CanJoinVoiceChannelResponse{}
	mi := &file_api_permission_v1_permission_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanJoinVoiceChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanJoinVoiceChannelResponse) ProtoMessage() {}

func (x *CanJoinVoiceChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_permission_v1_permission_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanJoinVoiceChannelResponse.ProtoReflect.Descriptor instead.
func (*CanJoinVoiceChannelResponse) Descriptor() ([]byte, []int) {
	return file_api_permission_v1_permission_proto_rawDescGZIP(), []int{1}
}

func (x *CanJoinVoiceChannelResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

var File_api_permission_v1_permission_proto protoreflect.FileDescriptor

const file_api_permission_v1_permission_proto_rawDesc = "" +
	"\n" +
	"\"api/permission/v1/permission.proto\x12\x12mint.permission.v1\"w\n" +
	"\x1aCanJoinVoiceChannelRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"7\n" +
	"\x1bCanJoinVoiceChannelResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed2\x8b\x01\n" +
	"\x11PermissionService\x12v\n" +
	"\x13CanJoinVoiceChannel\x12..mint.permission.v1.CanJoinVoiceChannelRequest\x1a/.mint.permission.v1.CanJoinVoiceChannelResponseB9Z7github.com/c4erries/mint/api/permission/v1;permissionv1b\x06proto3"

var (
	file_api_permission_v1_permission_proto_rawDescOnce sync.Once
	file_api_permission_v1_permission_proto_rawDescData []byte
)

func file_api_permission_v1_permission_proto_rawDescGZIP() []byte {
	file_api_permission_v1_permission_proto_rawDescOnce.Do(func() {
		file_api_permission_v1_permission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_permission_v1_permission_proto_rawDesc), len(file_api_permission_v1_permission_proto_rawDesc)))
	})
	return file_api_permission_v1_permission_proto_rawDescData
}

var file_api_permission_v1_permission_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_permission_v1_permission_proto_goTypes = []any{
	(*CanJoinVoiceChannelRequest)(nil),  // 0: mint.permission.v1.CanJoinVoiceChannelRequest
	(*CanJoinVoiceChannelResponse)(nil), // 1: mint.permission.v1.CanJoinVoiceChannelResponse
}
var file_api_permission_v1_permission_proto_depIdxs = []int32{
	0, // 0: mint.permission.v1.PermissionService.CanJoinVoiceChannel:input_type -> mint.permission.v1.CanJoinVoiceChannelRequest
	1, // 1: mint.permission.v1.PermissionService.CanJoinVoiceChannel:output_type -> mint.permission.v1.CanJoinVoiceChannelResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_permission_v1_permission_proto_init() }
func file_api_permission_v1_permission_proto_init() {
	if File_api_permission_v1_permission_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_permission_v1_permission_proto_rawDesc), len(file_api_permission_v1_permission_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_permission_v1_permission_proto_goTypes,
		DependencyIndexes: file_api_permission_v1_permission_proto_depIdxs,
		MessageInfos:      file_api_permission_v1_permission_proto_msgTypes,
	}.Build()
	File_api_permission_v1_permission_proto = out.File
	file_api_permission_v1_permission_proto_goTypes = nil
	file_api_permission_v1_permission_proto_depIdxs = nil
}
